import * as AwsConstant from './AwsConstant';

const MessageRole = Object.freeze({
  USER: {
    value: 'user',
    icon: 'mdi-account',
    i18nTitle: '__fieldUser',
    i18nSubtitle: '__subtitleMessageRoleUser',
  },
  ASSISTANT: {
    value: 'assistant',
    icon: 'mdi-face-agent',
    i18nTitle: '__fieldAssistant',
    i18nSubtitle: '__subtitleMessageRoleAssistant',
  },
});

const CredentialType = Object.freeze({
  ACCESS_KEY: {
    i18nTitle: '__fieldCredentialTypeAccessKey',
    value: 'accessKey',
    i18nSubtitle: '__subtitleCredentialTypeAccessKey',
  },
  IAM_ROLE: {
    i18nTitle: '__fieldCredentialTypeIamRole',
    value: 'iamRole',
    i18nSubtitle: '__subtitleCredentialTypeIamRole',
  },
});

const DefaultParams = Object.freeze({
  MAX_TOKENS: {
    default: 1024,
    min: 128,
    max: 131072,
    step: 1,
  },
  TEMPERATURE: {
    default: 1,
    min: 0,
    max: 1,
    step: 0.1,
  },
  TOP_K: {
    default: 250,
    min: 0,
    max: 500,
    step: 1,
  },
  TOP_P: {
    default: 0.999,
    min: 0,
    max: 1,
    step: 0.001,
  },
  FREQUENCY_PENALTY: {
    default: 0,
    min: -2,
    max: 2,
    step: 0.1,
  },
  PRESENCE_PENALTY: {
    default: 0,
    min: -2,
    max: 2,
    step: 0.1,
  },
});

const ThinkingEffort = Object.freeze({
  NONE: {
    i18nTitle: '__titleThinkingEffortNone',
    i18nSubtitle: '__subtitleThinkingEffortNone',
    value: 'none',
  },
  LOW: {
    i18nTitle: '__titleThinkingEffortLow',
    i18nSubtitle: '__subtitleThinkingEffortLow',
    value: 'low',
  },
  MEDIUM: {
    i18nTitle: '__titleThinkingEffortMedium',
    i18nSubtitle: '__subtitleThinkingEffortMedium',
    value: 'medium',
  },
  HIGH: {
    i18nTitle: '__titleThinkingEffortHigh',
    i18nSubtitle: '__subtitleThinkingEffortHigh',
    value: 'high',
  },
  XHIGH: {
    i18nTitle: '__titleThinkingEffortXhigh',
    i18nSubtitle: '__subtitleThinkingEffortXhigh',
    value: 'xhigh',
  },
  MAX: {
    i18nTitle: '__titleThinkingEffortMax',
    i18nSubtitle: '__subtitleThinkingEffortMax',
    value: 'max',
  },
});

const BedrockAnthropicModel = Object.freeze({
  GLOBAL_CLAUDE_SONNET_4_6: {
    title: 'Global Anthropic Claude Sonnet 4.6',
    value: 'global.anthropic.claude-sonnet-4-6',
    provider: 'Anthropic',
    thinking: {
      supported: true,
      canDisable: true,
      budgetTokens: {
        default: 1024,
        min: 1024,
        max: 63999,
        step: 1,
      },
    },
    supportedRegions: [
      AwsConstant.Region.AF_SOUTH_1,
      AwsConstant.Region.AP_EAST_2,
      AwsConstant.Region.AP_NORTHEAST_1,
      AwsConstant.Region.AP_NORTHEAST_2,
      AwsConstant.Region.AP_NORTHEAST_3,
      AwsConstant.Region.AP_SOUTH_1,
      AwsConstant.Region.AP_SOUTH_2,
      AwsConstant.Region.AP_SOUTHEAST_1,
      AwsConstant.Region.AP_SOUTHEAST_2,
      AwsConstant.Region.AP_SOUTHEAST_3,
      AwsConstant.Region.AP_SOUTHEAST_4,
      AwsConstant.Region.AP_SOUTHEAST_5,
      AwsConstant.Region.AP_SOUTHEAST_6,
      AwsConstant.Region.AP_SOUTHEAST_7,
      AwsConstant.Region.CA_CENTRAL_1,
      AwsConstant.Region.CA_WEST_1,
      AwsConstant.Region.EU_CENTRAL_1,
      AwsConstant.Region.EU_CENTRAL_2,
      AwsConstant.Region.EU_NORTH_1,
      AwsConstant.Region.EU_SOUTH_1,
      AwsConstant.Region.EU_SOUTH_2,
      AwsConstant.Region.EU_WEST_1,
      AwsConstant.Region.EU_WEST_2,
      AwsConstant.Region.EU_WEST_3,
      AwsConstant.Region.IL_CENTRAL_1,
      AwsConstant.Region.ME_CENTRAL_1,
      AwsConstant.Region.ME_SOUTH_1,
      AwsConstant.Region.MX_CENTRAL_1,
      AwsConstant.Region.SA_EAST_1,
      AwsConstant.Region.US_EAST_1,
      AwsConstant.Region.US_EAST_2,
      AwsConstant.Region.US_WEST_1,
      AwsConstant.Region.US_WEST_2,
    ],
    maxTokens: {
      default: 1024,
      defaultForThinking: 2048,
      min: 128,
      max: 64000,
      step: 1,
    },
    temperature: {
      default: 1,
      fixedForThinking: 1,
      min: 0,
      max: 1,
      step: 0.1,
    },
    topK: {
      default: 250,
      min: 0,
      max: 500,
      step: 1,
    },
    topP: {
      default: 0.999,
      min: 0,
      minForThinking: 0.95,
      max: 1,
      step: 0.1,
      stepForThinking: 0.01,
    },
  },
  GLOBAL_CLAUDE_SONNET_4_5: {
    title: 'Global Claude Sonnet 4.5',
    value: 'global.anthropic.claude-sonnet-4-5-20250929-v1:0',
    provider: 'Anthropic',
    thinking: {
      supported: true,
      canDisable: true,
      budgetTokens: {
        default: 1024,
        min: 1024,
        max: 63999,
        step: 1,
      },
    },
    supportedRegions: [
      AwsConstant.Region.AF_SOUTH_1,
      AwsConstant.Region.AP_EAST_2,
      AwsConstant.Region.AP_NORTHEAST_1,
      AwsConstant.Region.AP_NORTHEAST_2,
      AwsConstant.Region.AP_NORTHEAST_3,
      AwsConstant.Region.AP_SOUTH_1,
      AwsConstant.Region.AP_SOUTH_2,
      AwsConstant.Region.AP_SOUTHEAST_1,
      AwsConstant.Region.AP_SOUTHEAST_2,
      AwsConstant.Region.AP_SOUTHEAST_3,
      AwsConstant.Region.AP_SOUTHEAST_4,
      AwsConstant.Region.AP_SOUTHEAST_5,
      AwsConstant.Region.AP_SOUTHEAST_6,
      AwsConstant.Region.AP_SOUTHEAST_7,
      AwsConstant.Region.CA_CENTRAL_1,
      AwsConstant.Region.CA_WEST_1,
      AwsConstant.Region.EU_CENTRAL_1,
      AwsConstant.Region.EU_CENTRAL_2,
      AwsConstant.Region.EU_NORTH_1,
      AwsConstant.Region.EU_SOUTH_1,
      AwsConstant.Region.EU_SOUTH_2,
      AwsConstant.Region.EU_WEST_1,
      AwsConstant.Region.EU_WEST_2,
      AwsConstant.Region.EU_WEST_3,
      AwsConstant.Region.IL_CENTRAL_1,
      AwsConstant.Region.ME_CENTRAL_1,
      AwsConstant.Region.ME_SOUTH_1,
      AwsConstant.Region.MX_CENTRAL_1,
      AwsConstant.Region.SA_EAST_1,
      AwsConstant.Region.US_EAST_1,
      AwsConstant.Region.US_EAST_2,
      AwsConstant.Region.US_WEST_1,
      AwsConstant.Region.US_WEST_2,
    ],
    maxTokens: {
      default: 1024,
      defaultForThinking: 2048,
      min: 128,
      max: 64000,
      step: 1,
    },
    temperature: {
      default: 1,
      fixedForThinking: 1,
      min: 0,
      max: 1,
      step: 0.1,
    },
    topK: {
      default: 250,
      min: 0,
      max: 500,
      step: 1,
    },
    topP: {
      default: 0.999,
      min: 0,
      minForThinking: 0.95,
      max: 1,
      step: 0.1,
      stepForThinking: 0.01,
    },
  },
  GLOBAL_CLAUDE_HAIKU_4_5: {
    title: 'Global Anthropic Claude Haiku 4.5',
    value: 'global.anthropic.claude-haiku-4-5-20251001-v1:0',
    provider: 'Anthropic',
    thinking: {
      supported: true,
      canDisable: true,
      budgetTokens: {
        default: 1024,
        min: 1024,
        max: 63999,
        step: 1,
      },
    },
    supportedRegions: [
      AwsConstant.Region.AF_SOUTH_1,
      AwsConstant.Region.AP_EAST_2,
      AwsConstant.Region.AP_NORTHEAST_1,
      AwsConstant.Region.AP_NORTHEAST_2,
      AwsConstant.Region.AP_NORTHEAST_3,
      AwsConstant.Region.AP_SOUTH_1,
      AwsConstant.Region.AP_SOUTH_2,
      AwsConstant.Region.AP_SOUTHEAST_1,
      AwsConstant.Region.AP_SOUTHEAST_2,
      AwsConstant.Region.AP_SOUTHEAST_3,
      AwsConstant.Region.AP_SOUTHEAST_4,
      AwsConstant.Region.AP_SOUTHEAST_5,
      AwsConstant.Region.AP_SOUTHEAST_6,
      AwsConstant.Region.AP_SOUTHEAST_7,
      AwsConstant.Region.CA_CENTRAL_1,
      AwsConstant.Region.CA_WEST_1,
      AwsConstant.Region.EU_CENTRAL_1,
      AwsConstant.Region.EU_CENTRAL_2,
      AwsConstant.Region.EU_NORTH_1,
      AwsConstant.Region.EU_SOUTH_1,
      AwsConstant.Region.EU_SOUTH_2,
      AwsConstant.Region.EU_WEST_1,
      AwsConstant.Region.EU_WEST_2,
      AwsConstant.Region.EU_WEST_3,
      AwsConstant.Region.IL_CENTRAL_1,
      AwsConstant.Region.ME_CENTRAL_1,
      AwsConstant.Region.ME_SOUTH_1,
      AwsConstant.Region.MX_CENTRAL_1,
      AwsConstant.Region.SA_EAST_1,
      AwsConstant.Region.US_EAST_1,
      AwsConstant.Region.US_EAST_2,
      AwsConstant.Region.US_WEST_1,
      AwsConstant.Region.US_WEST_2,
    ],
    maxTokens: {
      default: 1024,
      defaultForThinking: 2048,
      min: 128,
      max: 64000,
      step: 1,
    },
    temperature: {
      default: 1,
      fixedForThinking: 1,
      min: 0,
      max: 1,
      step: 0.1,
    },
    topK: {
      default: 250,
      min: 0,
      max: 500,
      step: 1,
    },
    topP: {
      default: 0.999,
      min: 0,
      minForThinking: 0.95,
      max: 1,
      step: 0.1,
      stepForThinking: 0.01,
    },
  },
  GLOBAL_CLAUDE_OPUS_4_8: {
    title: 'Global Claude Opus 4.8',
    value: 'global.anthropic.claude-opus-4-8',
    provider: 'Anthropic',
    thinking: {
      supported: true,
      canDisable: true,
      supportedEfforts: [
        ThinkingEffort.LOW.value,
        ThinkingEffort.MEDIUM.value,
        ThinkingEffort.HIGH.value,
        ThinkingEffort.XHIGH.value,
        ThinkingEffort.MAX.value,
      ],
    },
    supportedRegions: [
      AwsConstant.Region.AF_SOUTH_1,
      AwsConstant.Region.AP_EAST_2,
      AwsConstant.Region.AP_NORTHEAST_1,
      AwsConstant.Region.AP_NORTHEAST_2,
      AwsConstant.Region.AP_NORTHEAST_3,
      AwsConstant.Region.AP_SOUTH_1,
      AwsConstant.Region.AP_SOUTH_2,
      AwsConstant.Region.AP_SOUTHEAST_1,
      AwsConstant.Region.AP_SOUTHEAST_2,
      AwsConstant.Region.AP_SOUTHEAST_3,
      AwsConstant.Region.AP_SOUTHEAST_4,
      AwsConstant.Region.AP_SOUTHEAST_5,
      AwsConstant.Region.AP_SOUTHEAST_6,
      AwsConstant.Region.AP_SOUTHEAST_7,
      AwsConstant.Region.CA_CENTRAL_1,
      AwsConstant.Region.CA_WEST_1,
      AwsConstant.Region.EU_CENTRAL_1,
      AwsConstant.Region.EU_CENTRAL_2,
      AwsConstant.Region.EU_NORTH_1,
      AwsConstant.Region.EU_SOUTH_1,
      AwsConstant.Region.EU_SOUTH_2,
      AwsConstant.Region.EU_WEST_1,
      AwsConstant.Region.EU_WEST_2,
      AwsConstant.Region.EU_WEST_3,
      AwsConstant.Region.IL_CENTRAL_1,
      AwsConstant.Region.ME_CENTRAL_1,
      AwsConstant.Region.ME_SOUTH_1,
      AwsConstant.Region.MX_CENTRAL_1,
      AwsConstant.Region.SA_EAST_1,
      AwsConstant.Region.US_EAST_1,
      AwsConstant.Region.US_EAST_2,
      AwsConstant.Region.US_WEST_1,
      AwsConstant.Region.US_WEST_2,
    ],
    maxTokens: {
      default: 1024,
      defaultForThinking: 2048,
      min: 128,
      max: 128000,
      step: 1,
    },
  },
  GLOBAL_CLAUDE_OPUS_4_7: {
    title: 'Global Claude Opus 4.7',
    value: 'global.anthropic.claude-opus-4-7',
    provider: 'Anthropic',
    thinking: {
      supported: true,
      canDisable: true,
      supportedEfforts: [
        ThinkingEffort.LOW.value,
        ThinkingEffort.MEDIUM.value,
        ThinkingEffort.HIGH.value,
        ThinkingEffort.XHIGH.value,
        ThinkingEffort.MAX.value,
      ],
    },
    supportedRegions: [
      AwsConstant.Region.AF_SOUTH_1,
      AwsConstant.Region.AP_EAST_2,
      AwsConstant.Region.AP_NORTHEAST_1,
      AwsConstant.Region.AP_NORTHEAST_2,
      AwsConstant.Region.AP_NORTHEAST_3,
      AwsConstant.Region.AP_SOUTH_1,
      AwsConstant.Region.AP_SOUTH_2,
      AwsConstant.Region.AP_SOUTHEAST_1,
      AwsConstant.Region.AP_SOUTHEAST_2,
      AwsConstant.Region.AP_SOUTHEAST_3,
      AwsConstant.Region.AP_SOUTHEAST_4,
      AwsConstant.Region.AP_SOUTHEAST_5,
      AwsConstant.Region.AP_SOUTHEAST_6,
      AwsConstant.Region.AP_SOUTHEAST_7,
      AwsConstant.Region.CA_CENTRAL_1,
      AwsConstant.Region.CA_WEST_1,
      AwsConstant.Region.EU_CENTRAL_1,
      AwsConstant.Region.EU_CENTRAL_2,
      AwsConstant.Region.EU_NORTH_1,
      AwsConstant.Region.EU_SOUTH_1,
      AwsConstant.Region.EU_SOUTH_2,
      AwsConstant.Region.EU_WEST_1,
      AwsConstant.Region.EU_WEST_2,
      AwsConstant.Region.EU_WEST_3,
      AwsConstant.Region.IL_CENTRAL_1,
      AwsConstant.Region.ME_CENTRAL_1,
      AwsConstant.Region.ME_SOUTH_1,
      AwsConstant.Region.MX_CENTRAL_1,
      AwsConstant.Region.SA_EAST_1,
      AwsConstant.Region.US_EAST_1,
      AwsConstant.Region.US_EAST_2,
      AwsConstant.Region.US_WEST_1,
      AwsConstant.Region.US_WEST_2,
    ],
    maxTokens: {
      default: 1024,
      defaultForThinking: 2048,
      min: 128,
      max: 128000,
      step: 1,
    },
  },
  GLOBAL_CLAUDE_OPUS_4_6_V1: {
    title: 'Global Claude Opus 4.6',
    value: 'global.anthropic.claude-opus-4-6-v1',
    provider: 'Anthropic',
    thinking: {
      supported: true,
      canDisable: true,
      budgetTokens: {
        default: 1024,
        min: 1024,
        max: 63999,
        step: 1,
      },
    },
    supportedRegions: [
      AwsConstant.Region.AF_SOUTH_1,
      AwsConstant.Region.AP_EAST_2,
      AwsConstant.Region.AP_NORTHEAST_1,
      AwsConstant.Region.AP_NORTHEAST_2,
      AwsConstant.Region.AP_NORTHEAST_3,
      AwsConstant.Region.AP_SOUTH_1,
      AwsConstant.Region.AP_SOUTH_2,
      AwsConstant.Region.AP_SOUTHEAST_1,
      AwsConstant.Region.AP_SOUTHEAST_2,
      AwsConstant.Region.AP_SOUTHEAST_3,
      AwsConstant.Region.AP_SOUTHEAST_4,
      AwsConstant.Region.AP_SOUTHEAST_5,
      AwsConstant.Region.AP_SOUTHEAST_6,
      AwsConstant.Region.AP_SOUTHEAST_7,
      AwsConstant.Region.CA_CENTRAL_1,
      AwsConstant.Region.CA_WEST_1,
      AwsConstant.Region.EU_CENTRAL_1,
      AwsConstant.Region.EU_CENTRAL_2,
      AwsConstant.Region.EU_NORTH_1,
      AwsConstant.Region.EU_SOUTH_1,
      AwsConstant.Region.EU_SOUTH_2,
      AwsConstant.Region.EU_WEST_1,
      AwsConstant.Region.EU_WEST_2,
      AwsConstant.Region.EU_WEST_3,
      AwsConstant.Region.IL_CENTRAL_1,
      AwsConstant.Region.ME_CENTRAL_1,
      AwsConstant.Region.ME_SOUTH_1,
      AwsConstant.Region.MX_CENTRAL_1,
      AwsConstant.Region.SA_EAST_1,
      AwsConstant.Region.US_EAST_1,
      AwsConstant.Region.US_EAST_2,
      AwsConstant.Region.US_WEST_1,
      AwsConstant.Region.US_WEST_2,
    ],
    maxTokens: {
      default: 1024,
      defaultForThinking: 2048,
      min: 128,
      max: 128000,
      step: 1,
    },
    temperature: {
      default: 1,
      fixedForThinking: 1,
      min: 0,
      max: 1,
      step: 0.1,
    },
    topK: {
      default: 250,
      min: 0,
      max: 500,
      step: 1,
    },
    topP: {
      default: 0.999,
      min: 0,
      minForThinking: 0.95,
      max: 1,
      step: 0.1,
      stepForThinking: 0.01,
    },
  },
  JP_CLAUDE_SONNET_4_6: {
    title: 'JP Anthropic Claude Sonnet 4.6',
    value: 'jp.anthropic.claude-sonnet-4-6',
    provider: 'Anthropic',
    thinking: {
      supported: true,
      canDisable: true,
      budgetTokens: {
        default: 1024,
        min: 1024,
        max: 63999,
        step: 1,
      },
    },
    supportedRegions: [
      AwsConstant.Region.AP_NORTHEAST_1,
      AwsConstant.Region.AP_NORTHEAST_3,
    ],
    maxTokens: {
      default: 1024,
      defaultForThinking: 2048,
      min: 128,
      max: 64000,
      step: 1,
    },
    temperature: {
      default: 1,
      fixedForThinking: 1,
      min: 0,
      max: 1,
      step: 0.1,
    },
    topK: {
      default: 250,
      min: 0,
      max: 500,
      step: 1,
    },
    topP: {
      default: 0.999,
      min: 0,
      minForThinking: 0.95,
      max: 1,
      step: 0.1,
      stepForThinking: 0.01,
    },
  },
  JP_CLAUDE_SONNET_4_5: {
    title: 'JP Anthropic Claude Sonnet 4.5',
    value: 'jp.anthropic.claude-sonnet-4-5-20250929-v1:0',
    provider: 'Anthropic',
    thinking: {
      supported: true,
      canDisable: true,
      budgetTokens: {
        default: 1024,
        min: 1024,
        max: 63999,
        step: 1,
      },
    },
    supportedRegions: [
      AwsConstant.Region.AP_NORTHEAST_1,
      AwsConstant.Region.AP_NORTHEAST_3,
    ],
    maxTokens: {
      default: 1024,
      defaultForThinking: 2048,
      min: 128,
      max: 64000,
      step: 1,
    },
    temperature: {
      default: 1,
      fixedForThinking: 1,
      min: 0,
      max: 1,
      step: 0.1,
    },
    topK: {
      default: 250,
      min: 0,
      max: 500,
      step: 1,
    },
    topP: {
      default: 0.999,
      min: 0,
      minForThinking: 0.95,
      max: 1,
      step: 0.1,
      stepForThinking: 0.01,
    },
  },
  JP_CLAUDE_HAIKU_4_5: {
    title: 'JP Anthropic Claude Haiku 4.5',
    value: 'jp.anthropic.claude-haiku-4-5-20251001-v1:0',
    provider: 'Anthropic',
    thinking: {
      supported: true,
      canDisable: true,
      budgetTokens: {
        default: 1024,
        min: 1024,
        max: 63999,
        step: 1,
      },
    },
    supportedRegions: [
      AwsConstant.Region.AP_NORTHEAST_1,
      AwsConstant.Region.AP_NORTHEAST_3,
    ],
    maxTokens: {
      default: 1024,
      defaultForThinking: 2048,
      min: 128,
      max: 64000,
      step: 1,
    },
    temperature: {
      default: 1,
      fixedForThinking: 1,
      min: 0,
      max: 1,
      step: 0.1,
    },
    topK: {
      default: 250,
      min: 0,
      max: 500,
      step: 1,
    },
    topP: {
      default: 0.999,
      min: 0,
      minForThinking: 0.95,
      max: 1,
      step: 0.1,
      stepForThinking: 0.01,
    },
  },
  US_CLAUDE_OPUS_4_8: {
    title: 'US Anthropic Claude Opus 4.8',
    value: 'us.anthropic.claude-opus-4-8',
    provider: 'Anthropic',
    thinking: {
      supported: true,
      canDisable: true,
      supportedEfforts: [
        ThinkingEffort.LOW.value,
        ThinkingEffort.MEDIUM.value,
        ThinkingEffort.HIGH.value,
        ThinkingEffort.XHIGH.value,
        ThinkingEffort.MAX.value,
      ],
    },
    supportedRegions: [
      AwsConstant.Region.CA_CENTRAL_1,
      AwsConstant.Region.CA_WEST_1,
      AwsConstant.Region.US_EAST_1,
      AwsConstant.Region.US_EAST_2,
      AwsConstant.Region.US_WEST_1,
      AwsConstant.Region.US_WEST_2,
    ],
    maxTokens: {
      default: 1024,
      defaultForThinking: 2048,
      min: 128,
      max: 128000,
      step: 1,
    },
  },
  US_CLAUDE_OPUS_4_7: {
    title: 'US Anthropic Claude Opus 4.7',
    value: 'us.anthropic.claude-opus-4-7',
    provider: 'Anthropic',
    thinking: {
      supported: true,
      canDisable: true,
      supportedEfforts: [
        ThinkingEffort.LOW.value,
        ThinkingEffort.MEDIUM.value,
        ThinkingEffort.HIGH.value,
        ThinkingEffort.XHIGH.value,
        ThinkingEffort.MAX.value,
      ],
    },
    supportedRegions: [
      AwsConstant.Region.CA_CENTRAL_1,
      AwsConstant.Region.CA_WEST_1,
      AwsConstant.Region.US_EAST_1,
      AwsConstant.Region.US_EAST_2,
      AwsConstant.Region.US_WEST_1,
      AwsConstant.Region.US_WEST_2,
    ],
    maxTokens: {
      default: 1024,
      defaultForThinking: 2048,
      min: 128,
      max: 128000,
      step: 1,
    },
  },
  US_CLAUDE_SONNET_4_6: {
    title: 'US Anthropic Claude Sonnet 4.6',
    value: 'us.anthropic.claude-sonnet-4-6',
    provider: 'Anthropic',
    thinking: {
      supported: true,
      canDisable: true,
      budgetTokens: {
        default: 1024,
        min: 1024,
        max: 63999,
        step: 1,
      },
    },
    supportedRegions: [
      AwsConstant.Region.CA_CENTRAL_1,
      AwsConstant.Region.CA_WEST_1,
      AwsConstant.Region.US_EAST_1,
      AwsConstant.Region.US_EAST_2,
      AwsConstant.Region.US_WEST_1,
      AwsConstant.Region.US_WEST_2,
    ],
    maxTokens: {
      default: 1024,
      defaultForThinking: 2048,
      min: 128,
      max: 64000,
      step: 1,
    },
    temperature: {
      default: 1,
      fixedForThinking: 1,
      min: 0,
      max: 1,
      step: 0.1,
    },
    topK: {
      default: 250,
      min: 0,
      max: 500,
      step: 1,
    },
    topP: {
      default: 0.999,
      min: 0,
      minForThinking: 0.95,
      max: 1,
      step: 0.1,
      stepForThinking: 0.01,
    },
  },
  US_CLAUDE_SONNET_4_5: {
    title: 'US Anthropic Claude Sonnet 4.5',
    value: 'us.anthropic.claude-sonnet-4-5-20250929-v1:0',
    provider: 'Anthropic',
    thinking: {
      supported: true,
      canDisable: true,
      budgetTokens: {
        default: 1024,
        min: 1024,
        max: 63999,
        step: 1,
      },
    },
    supportedRegions: [
      AwsConstant.Region.CA_CENTRAL_1,
      AwsConstant.Region.US_EAST_1,
      AwsConstant.Region.US_EAST_2,
      AwsConstant.Region.US_GOV_EAST_1,
      AwsConstant.Region.US_GOV_WEST_1,
      AwsConstant.Region.US_WEST_1,
      AwsConstant.Region.US_WEST_2,
    ],
    maxTokens: {
      default: 1024,
      defaultForThinking: 2048,
      min: 128,
      max: 64000,
      step: 1,
    },
    temperature: {
      default: 1,
      fixedForThinking: 1,
      min: 0,
      max: 1,
      step: 0.1,
    },
    topK: {
      default: 250,
      min: 0,
      max: 500,
      step: 1,
    },
    topP: {
      default: 0.999,
      min: 0,
      minForThinking: 0.95,
      max: 1,
      step: 0.1,
      stepForThinking: 0.01,
    },
  },
  US_CLAUDE_HAIKU_4_5: {
    title: 'US Anthropic Claude Haiku 4.5',
    value: 'us.anthropic.claude-haiku-4-5-20251001-v1:0',
    provider: 'Anthropic',
    thinking: {
      supported: true,
      canDisable: true,
      budgetTokens: {
        default: 1024,
        min: 1024,
        max: 63999,
        step: 1,
      },
    },
    supportedRegions: [
      AwsConstant.Region.CA_CENTRAL_1,
      AwsConstant.Region.US_EAST_1,
      AwsConstant.Region.US_EAST_2,
      AwsConstant.Region.US_WEST_1,
      AwsConstant.Region.US_WEST_2,
    ],
    maxTokens: {
      default: 1024,
      defaultForThinking: 2048,
      min: 128,
      max: 64000,
      step: 1,
    },
    temperature: {
      default: 1,
      fixedForThinking: 1,
      min: 0,
      max: 1,
      step: 0.1,
    },
    topK: {
      default: 250,
      min: 0,
      max: 500,
      step: 1,
    },
    topP: {
      default: 0.999,
      min: 0,
      minForThinking: 0.95,
      max: 1,
      step: 0.1,
      stepForThinking: 0.01,
    },
  },
  US_CLAUDE_OPUS_4_6_V1: {
    title: 'US Anthropic Claude Opus 4.6',
    value: 'us.anthropic.claude-opus-4-6-v1',
    provider: 'Anthropic',
    thinking: {
      supported: true,
      canDisable: true,
      budgetTokens: {
        default: 1024,
        min: 1024,
        max: 63999,
        step: 1,
      },
    },
    supportedRegions: [
      AwsConstant.Region.CA_CENTRAL_1,
      AwsConstant.Region.CA_WEST_1,
      AwsConstant.Region.US_EAST_1,
      AwsConstant.Region.US_EAST_2,
      AwsConstant.Region.US_WEST_1,
      AwsConstant.Region.US_WEST_2,
    ],
    maxTokens: {
      default: 1024,
      defaultForThinking: 2048,
      min: 128,
      max: 128000,
      step: 1,
    },
    temperature: {
      default: 1,
      fixedForThinking: 1,
      min: 0,
      max: 1,
      step: 0.1,
    },
    topK: {
      default: 250,
      min: 0,
      max: 500,
      step: 1,
    },
    topP: {
      default: 0.999,
      min: 0,
      minForThinking: 0.95,
      max: 1,
      step: 0.1,
      stepForThinking: 0.01,
    },
  },
  US_CLAUDE_OPUS_4_1: {
    title: 'US Claude Opus 4.1',
    value: 'us.anthropic.claude-opus-4-1-20250805-v1:0',
    provider: 'Anthropic',
    thinking: {
      supported: true,
      canDisable: true,
      budgetTokens: {
        default: 1024,
        min: 1024,
        max: 63999,
        step: 1,
      },
    },
    supportedRegions: [
      AwsConstant.Region.US_EAST_1,
      AwsConstant.Region.US_EAST_2,
      AwsConstant.Region.US_WEST_2,
    ],
    maxTokens: {
      default: 1024,
      defaultForThinking: 2048,
      min: 128,
      max: 32000,
      step: 1,
    },
    temperature: {
      default: 1,
      fixedForThinking: 1,
      min: 0,
      max: 1,
      step: 0.1,
    },
    topK: {
      default: 250,
      min: 0,
      max: 500,
      step: 1,
    },
    topP: {
      default: 0.999,
      min: 0,
      minForThinking: 0.95,
      max: 1,
      step: 0.1,
      stepForThinking: 0.01,
    },
  },
});

const BedrockLlamaModel = Object.freeze({
  US_LLAMA_4_MAVERICK_17B: {
    title: 'US Llama 4 Maverick 17B',
    value: 'us.meta.llama4-maverick-17b-instruct-v1:0',
    provider: 'Meta',
    thinking: {
      supported: false,
      canDisable: false,
    },
    supportedRegions: [
      AwsConstant.Region.US_EAST_1,
      AwsConstant.Region.US_EAST_2,
      AwsConstant.Region.US_WEST_2,
    ],
    maxTokens: {
      default: 512,
      min: 128,
      max: 4096,
      step: 1,
    },
    temperature: {
      default: 0.5,
      min: 0,
      max: 1,
      step: 0.1,
    },
    topP: {
      default: 0.9,
      min: 0,
      max: 1,
      step: 0.1,
    },
  },
  US_LLAMA_4_SCOUT_17B: {
    title: 'US Llama 4 Scout 17B',
    value: 'us.meta.llama4-scout-17b-instruct-v1:0',
    provider: 'Meta',
    thinking: {
      supported: false,
      canDisable: false,
    },
    supportedRegions: [
      AwsConstant.Region.US_EAST_1,
      AwsConstant.Region.US_EAST_2,
      AwsConstant.Region.US_WEST_2,
    ],
    maxTokens: {
      default: 512,
      min: 128,
      max: 2048,
      step: 1,
    },
    temperature: {
      default: 0.5,
      min: 0,
      max: 1,
      step: 0.1,
    },
    topP: {
      default: 0.9,
      min: 0,
      max: 1,
      step: 0.1,
    },
  },
  US_LLAMA_3_3_70B: {
    title: 'US Llama 3.3 70B',
    value: 'us.meta.llama3-3-70b-instruct-v1:0',
    provider: 'Meta',
    thinking: {
      supported: false,
      canDisable: false,
    },
    supportedRegions: [
      AwsConstant.Region.US_EAST_1,
      AwsConstant.Region.US_EAST_2,
      AwsConstant.Region.US_WEST_2,
    ],
    maxTokens: {
      default: 512,
      min: 128,
      max: 2048,
      step: 1,
    },
    temperature: {
      default: 0.5,
      min: 0,
      max: 1,
      step: 0.1,
    },
    topP: {
      default: 0.9,
      min: 0,
      max: 1,
      step: 0.1,
    },
  },
  LLAMA_3_3_70B: {
    title: 'Llama 3.3 70B',
    value: 'meta.llama3-3-70b-instruct-v1:0',
    provider: 'Meta',
    thinking: {
      supported: false,
      canDisable: false,
    },
    supportedRegions: [
      AwsConstant.Region.US_EAST_2,
    ],
    maxTokens: {
      default: 512,
      min: 128,
      max: 2048,
      step: 1,
    },
    temperature: {
      default: 0.5,
      min: 0,
      max: 1,
      step: 0.1,
    },
    topP: {
      default: 0.9,
      min: 0,
      max: 1,
      step: 0.1,
    },
  },
});

const BedrockGptOssModel = Object.freeze({
  GPT_OSS_20B_1_0: {
    title: 'OpenAI GPT OSS 20B 1.0',
    value: 'openai.gpt-oss-20b-1:0',
    provider: 'OpenAI',
    thinking: {
      supported: false,
      canDisable: false,
    },
    supportedRegions: [
      AwsConstant.Region.AP_NORTHEAST_1,
      AwsConstant.Region.AP_SOUTH_1,
      AwsConstant.Region.AP_SOUTHEAST_2,
      AwsConstant.Region.AP_SOUTHEAST_3,
      AwsConstant.Region.EU_CENTRAL_1,
      AwsConstant.Region.EU_NORTH_1,
      AwsConstant.Region.EU_SOUTH_1,
      AwsConstant.Region.EU_WEST_1,
      AwsConstant.Region.EU_WEST_2,
      AwsConstant.Region.SA_EAST_1,
      AwsConstant.Region.US_EAST_1,
      AwsConstant.Region.US_EAST_2,
      AwsConstant.Region.US_WEST_2,
    ],
    maxTokens: {
      default: 512,
      min: 128,
      max: 65536,
      step: 1,
    },
    temperature: {
      default: 1,
      min: 0,
      max: 1,
      step: 0.1,
    },
    topP: {
      default: 0.999,
      min: 0,
      max: 1,
      step: 0.001,
    },
  },
  GPT_OSS_120B_1_0: {
    title: 'OpenAI GPT OSS 120B 1.0',
    value: 'openai.gpt-oss-120b-1:0',
    provider: 'OpenAI',
    thinking: {
      supported: false,
      canDisable: false,
    },
    supportedRegions: [
      AwsConstant.Region.AP_NORTHEAST_1,
      AwsConstant.Region.AP_SOUTH_1,
      AwsConstant.Region.AP_SOUTHEAST_2,
      AwsConstant.Region.AP_SOUTHEAST_3,
      AwsConstant.Region.EU_CENTRAL_1,
      AwsConstant.Region.EU_NORTH_1,
      AwsConstant.Region.EU_SOUTH_1,
      AwsConstant.Region.EU_WEST_1,
      AwsConstant.Region.EU_WEST_2,
      AwsConstant.Region.SA_EAST_1,
      AwsConstant.Region.US_EAST_1,
      AwsConstant.Region.US_EAST_2,
      AwsConstant.Region.US_WEST_2,
    ],
    maxTokens: {
      default: 512,
      min: 128,
      max: 65536,
      step: 1,
    },
    temperature: {
      default: 1,
      min: 0,
      max: 1,
      step: 0.1,
    },
    topP: {
      default: 0.999,
      min: 0,
      max: 1,
      step: 0.001,
    },
  },
});

const BedrockNovaModel = Object.freeze({
  GLOBAL_NOVA_2_LITE_V1: {
    title: 'Global Nova 2 Lite',
    value: 'global.amazon.nova-2-lite-v1:0',
    provider: 'Nova',
    thinking: {
      supported: false,
      canDisable: false,
    },
    supportedRegions: [
      AwsConstant.Region.AP_EAST_2,
      AwsConstant.Region.AP_NORTHEAST_1,
      AwsConstant.Region.AP_NORTHEAST_2,
      AwsConstant.Region.AP_SOUTH_1,
      AwsConstant.Region.AP_SOUTHEAST_1,
      AwsConstant.Region.AP_SOUTHEAST_2,
      AwsConstant.Region.AP_SOUTHEAST_3,
      AwsConstant.Region.AP_SOUTHEAST_4,
      AwsConstant.Region.AP_SOUTHEAST_5,
      AwsConstant.Region.AP_SOUTHEAST_6,
      AwsConstant.Region.AP_SOUTHEAST_7,
      AwsConstant.Region.CA_CENTRAL_1,
      AwsConstant.Region.CA_WEST_1,
      AwsConstant.Region.EU_CENTRAL_1,
      AwsConstant.Region.EU_NORTH_1,
      AwsConstant.Region.EU_SOUTH_1,
      AwsConstant.Region.EU_SOUTH_2,
      AwsConstant.Region.EU_WEST_1,
      AwsConstant.Region.EU_WEST_2,
      AwsConstant.Region.EU_WEST_3,
      AwsConstant.Region.IL_CENTRAL_1,
      AwsConstant.Region.ME_CENTRAL_1,
      AwsConstant.Region.US_EAST_1,
      AwsConstant.Region.US_EAST_2,
      AwsConstant.Region.US_WEST_1,
      AwsConstant.Region.US_WEST_2,
    ],
    maxTokens: {
      default: 512,
      min: 128,
      max: 65000,
      step: 1,
    },
    temperature: {
      default: 0.7,
      min: 0,
      max: 1,
      step: 0.00001,
    },
    topK: {
      default: 0,
      min: 0,
      max: 128,
      step: 1,
    },
    topP: {
      default: 0.9,
      min: 0,
      max: 1,
      step: 0.1,
    },
  },
  US_NOVA_LITE_V1: {
    title: 'US Nova Lite',
    value: 'us.amazon.nova-lite-v1:0',
    provider: 'Nova',
    thinking: {
      supported: false,
      canDisable: false,
    },
    supportedRegions: [
      AwsConstant.Region.US_WEST_2,
      AwsConstant.Region.US_EAST_1,
      AwsConstant.Region.US_EAST_2,
    ],
    maxTokens: {
      default: 512,
      min: 128,
      max: 5120,
      step: 1,
    },
    temperature: {
      default: 0.7,
      min: 0,
      max: 1,
      step: 0.00001,
    },
    topK: {
      default: 0,
      min: 0,
      max: 128,
      step: 1,
    },
    topP: {
      default: 0.9,
      min: 0,
      max: 1,
      step: 0.1,
    },
  },
  US_NOVA_MICRO_V1: {
    title: 'US Nova Micro',
    value: 'us.amazon.nova-micro-v1:0',
    provider: 'Nova',
    thinking: {
      supported: false,
      canDisable: false,
    },
    supportedRegions: [
      AwsConstant.Region.US_WEST_2,
      AwsConstant.Region.US_EAST_1,
      AwsConstant.Region.US_EAST_2,
    ],
    maxTokens: {
      default: 512,
      min: 128,
      max: 5120,
      step: 1,
    },
    temperature: {
      default: 0.7,
      min: 0,
      max: 1,
      step: 0.00001,
    },
    topK: {
      default: 0,
      min: 0,
      max: 128,
      step: 1,
    },
    topP: {
      default: 0.9,
      min: 0,
      max: 1,
      step: 0.1,
    },
  },
  US_NOVA_PRO_V1: {
    title: 'US Nova Pro',
    value: 'us.amazon.nova-pro-v1:0',
    provider: 'Nova',
    thinking: {
      supported: false,
      canDisable: false,
    },
    supportedRegions: [
      AwsConstant.Region.US_WEST_2,
      AwsConstant.Region.US_EAST_1,
      AwsConstant.Region.US_EAST_2,
    ],
    latencyOptimizedRegions: [
      AwsConstant.Region.US_EAST_1,
      AwsConstant.Region.US_EAST_2,
    ],
    maxTokens: {
      default: 512,
      min: 128,
      max: 5120,
      step: 1,
    },
    temperature: {
      default: 0.7,
      min: 0,
      max: 1,
      step: 0.00001,
    },
    topK: {
      default: 0,
      min: 0,
      max: 128,
      step: 1,
    },
    topP: {
      default: 0.9,
      min: 0,
      max: 1,
      step: 0.1,
    },
  },
  NOVA_LITE_V1: {
    title: 'Nova Lite',
    value: 'amazon.nova-lite-v1:0',
    provider: 'Nova',
    thinking: {
      supported: false,
      canDisable: false,
    },
    supportedRegions: [
      AwsConstant.Region.US_EAST_1,
    ],
    maxTokens: {
      default: 512,
      min: 128,
      max: 5120,
      step: 1,
    },
    temperature: {
      default: 0.7,
      min: 0,
      max: 1,
      step: 0.00001,
    },
    topK: {
      default: 0,
      min: 0,
      max: 128,
      step: 1,
    },
    topP: {
      default: 0.9,
      min: 0,
      max: 1,
      step: 0.1,
    },
  },
  NOVA_MICRO_V1: {
    title: 'Nova Micro',
    value: 'amazon.nova-micro-v1:0',
    provider: 'Nova',
    thinking: {
      supported: false,
      canDisable: false,
    },
    supportedRegions: [
      AwsConstant.Region.US_EAST_1,
    ],
    maxTokens: {
      default: 512,
      min: 128,
      max: 5120,
      step: 1,
    },
    temperature: {
      default: 0.7,
      min: 0,
      max: 1,
      step: 0.00001,
    },
    topK: {
      default: 0,
      min: 0,
      max: 128,
      step: 1,
    },
    topP: {
      default: 0.9,
      min: 0,
      max: 1,
      step: 0.1,
    },
  },
  NOVA_PRO_V1: {
    title: 'Nova Pro',
    value: 'amazon.nova-pro-v1:0',
    provider: 'Nova',
    thinking: {
      supported: false,
      canDisable: false,
    },
    supportedRegions: [
      AwsConstant.Region.US_EAST_1,
    ],
    maxTokens: {
      default: 512,
      min: 128,
      max: 5120,
      step: 1,
    },
    temperature: {
      default: 0.7,
      min: 0,
      max: 1,
      step: 0.00001,
    },
    topK: {
      default: 0,
      min: 0,
      max: 128,
      step: 1,
    },
    topP: {
      default: 0.9,
      min: 0,
      max: 1,
      step: 0.1,
    },
  },
});

const GeminiModel = Object.freeze({
  GEMINI_3_5_FLASH: {
    title: 'Gemini 3.5 Flash',
    value: 'gemini-3.5-flash',
    provider: 'Google',
    thinking: {
      supported: true,
      canDisable: false,
      useBudgetTokens: false,
      useThinkingLevel: true,
    },
    maxTokens: {
      default: 1024,
      defaultForThinking: 2048,
      min: 128,
      max: 65536,
      step: 1,
    },
    temperature: {
      default: 0.2,
      min: 0,
      max: 2,
      step: 0.1,
    },
    topK: {
      default: 0,
      min: 0,
      max: 500,
      step: 1,
    },
    topP: {
      default: 0.9,
      min: 0,
      max: 1,
      step: 0.1,
    },
  },
  GEMINI_3_1_PRO_PREVIEW: {
    title: 'Gemini 3.1 Pro Preview',
    value: 'gemini-3.1-pro-preview',
    provider: 'Google',
    thinking: {
      supported: true,
      canDisable: false,
      useBudgetTokens: false,
      useThinkingLevel: true,
    },
    maxTokens: {
      default: 1024,
      defaultForThinking: 2048,
      min: 128,
      max: 65536,
      step: 1,
    },
    temperature: {
      default: 0.2,
      min: 0,
      max: 2,
      step: 0.1,
    },
    topK: {
      default: 0,
      min: 0,
      max: 500,
      step: 1,
    },
    topP: {
      default: 0.9,
      min: 0,
      max: 1,
      step: 0.1,
    },
  },
  GEMINI_3_1_FLASH_LITE: {
    title: 'Gemini 3.1 Flash Lite',
    value: 'gemini-3.1-flash-lite',
    provider: 'Google',
    thinking: {
      supported: true,
      canDisable: false,
      useBudgetTokens: false,
      useThinkingLevel: true,
    },
    maxTokens: {
      default: 1024,
      defaultForThinking: 2048,
      min: 128,
      max: 65536,
      step: 1,
    },
    temperature: {
      default: 0.2,
      min: 0,
      max: 2,
      step: 0.1,
    },
    topK: {
      default: 0,
      min: 0,
      max: 500,
      step: 1,
    },
    topP: {
      default: 0.9,
      min: 0,
      max: 1,
      step: 0.1,
    },
  },
  GEMINI_3_FLASH_PREVIEW: {
    title: 'Gemini 3 Flash Preview',
    value: 'gemini-3-flash-preview',
    provider: 'Google',
    thinking: {
      supported: true,
      canDisable: false,
      useBudgetTokens: false,
      useThinkingLevel: true,
    },
    maxTokens: {
      default: 1024,
      defaultForThinking: 2048,
      min: 128,
      max: 65536,
      step: 1,
    },
    temperature: {
      default: 0.2,
      min: 0,
      max: 2,
      step: 0.1,
    },
    topK: {
      default: 0,
      min: 0,
      max: 500,
      step: 1,
    },
    topP: {
      default: 0.9,
      min: 0,
      max: 1,
      step: 0.1,
    },
  },
  GEMINI_2_5_FLASH: {
    title: 'Gemini 2.5 Flash',
    value: 'gemini-2.5-flash',
    provider: 'Google',
    thinking: {
      supported: true,
      canDisable: true,
      useBudgetTokens: true,
      useThinkingLevel: false,
      budgetTokens: {
        default: 1024,
        min: 1,
        max: 24576,
        step: 1,
        fixedForDynamic: -1,
        fixedForDisabled: 0,
      },
    },
    maxTokens: {
      default: 1024,
      defaultForThinking: 2048,
      min: 128,
      max: 65536,
      step: 1,
    },
    temperature: {
      default: 0.2,
      min: 0,
      max: 2,
      step: 0.1,
    },
    topK: {
      default: 0,
      min: 0,
      max: 500,
      step: 1,
    },
    topP: {
      default: 0.9,
      min: 0,
      max: 1,
      step: 0.1,
    },
  },
  GEMINI_2_5_PRO: {
    title: 'Gemini 2.5 Pro',
    value: 'gemini-2.5-pro',
    provider: 'Google',
    thinking: {
      supported: true,
      canDisable: false,
      useBudgetTokens: true,
      useThinkingLevel: false,
      budgetTokens: {
        default: 1024,
        min: 128,
        max: 32768,
        step: 1,
        fixedForDynamic: -1,
      },
    },
    maxTokens: {
      default: 1024,
      defaultForThinking: 2048,
      min: 128,
      max: 65536,
      step: 1,
    },
    temperature: {
      default: 0.2,
      min: 0,
      max: 2,
      step: 0.1,
    },
    topK: {
      default: 0,
      min: 0,
      max: 500,
      step: 1,
    },
    topP: {
      default: 0.9,
      min: 0,
      max: 1,
      step: 0.1,
    },
  },
});

const OpenAiModel = Object.freeze({
  GPT_5_5: {
    title: 'OpenAI - GPT-5.5',
    value: 'gpt-5.5',
    provider: 'OpenAI',
    thinking: {
      supported: true,
      canDisable: true,
      defaultEffort: ThinkingEffort.MEDIUM.value,
      supportedEfforts: [
        ThinkingEffort.NONE.value,
        ThinkingEffort.LOW.value,
        ThinkingEffort.MEDIUM.value,
        ThinkingEffort.HIGH.value,
        ThinkingEffort.XHIGH.value,
      ],
    },
    maxTokens: {
      default: 1024,
      min: 128,
      max: 128000,
      step: 1,
    },
    temperature: {
      fixedValue: 1,
      min: 0,
      max: 2,
    },
    topP: {
      fixedValue: 1,
      min: 0,
      max: 1,
    },
  },
  GPT_5_4: {
    title: 'OpenAI - GPT-5.4',
    value: 'gpt-5.4',
    provider: 'OpenAI',
    thinking: {
      supported: true,
      canDisable: true,
      defaultEffort: ThinkingEffort.NONE.value,
      supportedEfforts: [
        ThinkingEffort.NONE.value,
        ThinkingEffort.LOW.value,
        ThinkingEffort.MEDIUM.value,
        ThinkingEffort.HIGH.value,
        ThinkingEffort.XHIGH.value,
      ],
    },
    maxTokens: {
      default: 1024,
      min: 128,
      max: 128000,
      step: 1,
    },
    temperature: {
      fixedValue: 1,
      min: 0,
      max: 2,
    },
    topP: {
      fixedValue: 1,
      min: 0,
      max: 1,
    },
  },
  GPT_5_4_MINI: {
    title: 'OpenAI - GPT-5.4 mini',
    value: 'gpt-5.4-mini',
    provider: 'OpenAI',
    thinking: {
      supported: true,
      canDisable: true,
      defaultEffort: ThinkingEffort.NONE.value,
      supportedEfforts: [
        ThinkingEffort.NONE.value,
        ThinkingEffort.LOW.value,
        ThinkingEffort.MEDIUM.value,
        ThinkingEffort.HIGH.value,
        ThinkingEffort.XHIGH.value,
      ],
    },
    maxTokens: {
      default: 1024,
      min: 128,
      max: 128000,
      step: 1,
    },
    temperature: {
      fixedValue: 1,
      min: 0,
      max: 2,
    },
    topP: {
      fixedValue: 1,
      min: 0,
      max: 1,
    },
  },
  GPT_5_4_NANO: {
    title: 'OpenAI - GPT-5.4 nano',
    value: 'gpt-5.4-nano',
    provider: 'OpenAI',
    thinking: {
      supported: true,
      canDisable: true,
      defaultEffort: ThinkingEffort.NONE.value,
      supportedEfforts: [
        ThinkingEffort.NONE.value,
        ThinkingEffort.LOW.value,
        ThinkingEffort.MEDIUM.value,
        ThinkingEffort.HIGH.value,
        ThinkingEffort.XHIGH.value,
      ],
    },
    maxTokens: {
      default: 1024,
      min: 128,
      max: 128000,
      step: 1,
    },
    temperature: {
      fixedValue: 1,
      min: 0,
      max: 2,
    },
    topP: {
      fixedValue: 1,
      min: 0,
      max: 1,
    },
  },
  GPT_5_2: {
    title: 'OpenAI - GPT-5.2',
    value: 'gpt-5.2',
    provider: 'OpenAI',
    thinking: {
      supported: true,
      canDisable: true,
      defaultEffort: ThinkingEffort.NONE.value,
      supportedEfforts: [
        ThinkingEffort.NONE.value,
        ThinkingEffort.LOW.value,
        ThinkingEffort.MEDIUM.value,
        ThinkingEffort.HIGH.value,
        ThinkingEffort.XHIGH.value,
      ],
    },
    maxTokens: {
      default: 1024,
      min: 128,
      max: 128000,
      step: 1,
    },
    temperature: {
      fixedValue: 1,
      min: 0,
      max: 2,
    },
    topP: {
      fixedValue: 1,
      min: 0,
      max: 1,
    },
  },
  GPT_5_1: {
    title: 'OpenAI - GPT-5.1',
    value: 'gpt-5.1',
    provider: 'OpenAI',
    thinking: {
      supported: true,
      canDisable: true,
      defaultEffort: ThinkingEffort.NONE.value,
      supportedEfforts: [
        ThinkingEffort.NONE.value,
        ThinkingEffort.LOW.value,
        ThinkingEffort.MEDIUM.value,
        ThinkingEffort.HIGH.value,
      ],
    },
    maxTokens: {
      default: 1024,
      min: 128,
      max: 128000,
      step: 1,
    },
    temperature: {
      fixedValue: 1,
      min: 0,
      max: 2,
    },
    topP: {
      fixedValue: 1,
      min: 0,
      max: 1,
    },
  },
  GPT_5_MINI: {
    title: 'OpenAI - GPT-5 mini',
    value: 'gpt-5-mini',
    provider: 'OpenAI',
    thinking: {
      supported: true,
      canDisable: false,
      defaultEffort: ThinkingEffort.MEDIUM.value,
      supportedEfforts: [
        ThinkingEffort.LOW.value,
        ThinkingEffort.MEDIUM.value,
        ThinkingEffort.HIGH.value,
      ],
    },
    maxTokens: {
      default: 1024,
      min: 128,
      max: 128000,
      step: 1,
    },
    temperature: {
      fixedValue: 1,
      min: 0,
      max: 2,
    },
    topP: {
      fixedValue: 1,
      min: 0,
      max: 1,
    },
  },
  GPT_5: {
    title: 'OpenAI - GPT-5',
    value: 'gpt-5',
    provider: 'OpenAI',
    thinking: {
      supported: true,
      canDisable: false,
      defaultEffort: ThinkingEffort.MEDIUM.value,
      supportedEfforts: [
        ThinkingEffort.LOW.value,
        ThinkingEffort.MEDIUM.value,
        ThinkingEffort.HIGH.value,
      ],
    },
    maxTokens: {
      default: 1024,
      min: 128,
      max: 128000,
      step: 1,
    },
    temperature: {
      fixedValue: 1,
      min: 0,
      max: 2,
    },
    topP: {
      fixedValue: 1,
      min: 0,
      max: 1,
    },
  },
  GPT_5_NANO: {
    title: 'OpenAI - GPT-5 nano',
    value: 'gpt-5-nano',
    provider: 'OpenAI',
    thinking: {
      supported: true,
      canDisable: false,
      defaultEffort: ThinkingEffort.MEDIUM.value,
      supportedEfforts: [
        ThinkingEffort.LOW.value,
        ThinkingEffort.MEDIUM.value,
        ThinkingEffort.HIGH.value,
      ],
    },
    maxTokens: {
      default: 1024,
      min: 128,
      max: 128000,
      step: 1,
    },
    temperature: {
      fixedValue: 1,
      min: 0,
      max: 2,
    },
    topP: {
      fixedValue: 1,
      min: 0,
      max: 1,
    },
  },
});

const Type = Object.freeze({
  BEDROCK_ANTHROPIC: {
    title: 'Amazon Bedrock - Anthropic',
    value: 'bedrock.anthropic',
    iconPath: '/images/icons/anthropic.svg',
    i18nSubtitle: '__subtitleLlmTypeBedrockAnthropic',
    i18nSecretInputFields: [
      '__fieldAwsSecretAccessKey',
    ],
    i18nValidateAction: '__actionValidateCredentials',
    i18nValidateMessage: '__messageCredentialsValidated',
    i18nValidating: '__actionValidating',
    allowAwsCredential: true,
    supportedMessageRoles: [
      MessageRole.ASSISTANT.value,
      MessageRole.USER.value,
    ],
    model: BedrockAnthropicModel,
  },
  BEDROCK_LLAMA: {
    title: 'Amazon Bedrock - Llama',
    value: 'bedrock.llama',
    iconPath: '/images/icons/meta.svg',
    i18nSubtitle: '__subtitleLlmTypeBedrockLlama',
    i18nSecretInputFields: [
      '__fieldAwsSecretAccessKey',
    ],
    i18nValidateAction: '__actionValidateCredentials',
    i18nValidateMessage: '__messageCredentialsValidated',
    i18nValidating: '__actionValidating',
    allowAwsCredential: true,
    supportedMessageRoles: [
      MessageRole.ASSISTANT.value,
      MessageRole.USER.value,
    ],
    model: BedrockLlamaModel,
  },
  BEDROCK_GPT_OSS: {
    title: 'Amazon Bedrock - GPT OSS',
    value: 'bedrock.gptoss',
    iconPath: '/images/icons/openai.svg',
    i18nSubtitle: '__subtitleLlmTypeBedrockGptOss',
    i18nSecretInputFields: [
      '__fieldAwsSecretAccessKey',
    ],
    i18nValidateAction: '__actionValidateCredentials',
    i18nValidateMessage: '__messageCredentialsValidated',
    i18nValidating: '__actionValidating',
    allowAwsCredential: true,
    supportedMessageRoles: [
      MessageRole.ASSISTANT.value,
      MessageRole.USER.value,
    ],
    model: BedrockGptOssModel,
  },
  BEDROCK_NOVA: {
    title: 'Amazon Bedrock - Nova',
    value: 'bedrock.nova',
    iconPath: '/images/icons/nova.svg',
    i18nSubtitle: '__subtitleLlmTypeBedrockNova',
    i18nSecretInputFields: [
      '__fieldAwsSecretAccessKey',
    ],
    i18nValidateAction: '__actionValidateCredentials',
    i18nValidateMessage: '__messageCredentialsValidated',
    i18nValidating: '__actionValidating',
    allowAwsCredential: true,
    supportedMessageRoles: [
      MessageRole.ASSISTANT.value,
      MessageRole.USER.value,
    ],
    model: BedrockNovaModel,
  },
  GEMINI: {
    title: 'Gemini',
    value: 'gemini',
    iconPath: '/images/icons/gemini.svg',
    i18nSubtitle: '__subtitleLlmTypeGemini',
    i18nSecretInputFields: [
      '__fieldApiKey',
    ],
    i18nValidateAction: '__actionValidateApiKey',
    i18nValidateMessage: '__messageApiKeyValidated',
    i18nValidating: '__actionValidating',
    allowAwsCredential: false,
    supportedMessageRoles: [
      MessageRole.USER.value,
    ],
    model: GeminiModel,
  },
  OLLAMA: {
    title: 'Ollama',
    value: 'ollama',
    iconPath: '/images/icons/ollama.svg',
    i18nSubtitle: '__subtitleLlmTypeOllama',
    i18nValidateAction: '__actionTestConnection',
    i18nValidateMessage: '__messageConnectionTested',
    i18nValidating: '__actionTesting',
    allowAwsCredential: false,
    supportedMessageRoles: [
      MessageRole.USER.value,
    ],
    model: {},
  },
  OPENAI: {
    title: 'OpenAI',
    value: 'openai',
    iconPath: '/images/icons/openai.svg',
    i18nSubtitle: '__subtitleLlmTypeOpenai',
    i18nValidateAction: '__actionValidateApiKey',
    i18nValidateMessage: '__messageApiKeyValidated',
    i18nValidating: '__actionValidating',
    i18nSecretInputFields: [
      '__fieldApiKey',
    ],
    allowAwsCredential: false,
    supportedMessageRoles: [
      MessageRole.USER.value,
    ],
    model: OpenAiModel,
  },
});

const ThinkingLevel = Object.freeze({
  LOW: {
    i18nTitle: '__titleThinkingLevelLow',
    i18nSubtitle: '__subtitleThinkingLevelLow',
    value: 'low',
  },
  HIGH: {
    i18nTitle: '__titleThinkingLevelHigh',
    i18nSubtitle: '__subtitleThinkingLevelHigh',
    value: 'high',
  },
});

const ThinkingBudgetMode = Object.freeze({
  DYNAMIC: {
    i18nTitle: '__titleThinkingBudgetModeDynamic',
    i18nSubtitle: '__subtitleThinkingBudgetModeDynamic',
    value: 'dynamic',
  },
  DISABLED: {
    i18nTitle: '__titleThinkingBudgetModeDisabled',
    i18nSubtitle: '__subtitleThinkingBudgetModeDisabled',
    value: 'disabled',
  },
  CUSTOM: {
    i18nTitle: '__titleThinkingBudgetModeCustom',
    i18nSubtitle: '__subtitleThinkingBudgetModeCustom',
    value: 'custom',
  },
});

const Model = Object.freeze({
  ...Object.values(BedrockAnthropicModel).reduce((acc, model) => ({ ...acc, [model.value]: model }), {}),
  ...Object.values(BedrockGptOssModel).reduce((acc, model) => ({ ...acc, [model.value]: model }), {}),
  ...Object.values(BedrockLlamaModel).reduce((acc, model) => ({ ...acc, [model.value]: model }), {}),
  ...Object.values(BedrockNovaModel).reduce((acc, model) => ({ ...acc, [model.value]: model }), {}),
  ...Object.values(GeminiModel).reduce((acc, model) => ({ ...acc, [model.value]: model }), {}),
  ...Object.values(OpenAiModel).reduce((acc, model) => ({ ...acc, [model.value]: model }), {}),
});

const BedrockPerformanceConfigLatencyOption = Object.freeze({
  STANDARD: {
    i18nTitle: '__titleStandard',
    value: 'standard',
    i18nSubtitle: '__subtitleLlmBedrockNovaPerformanceConfigLatencyStandard',
  },
  OPTIMIZED: {
    i18nTitle: '__titleOptimized',
    value: 'optimized',
    i18nSubtitle: '__subtitleLlmBedrockNovaPerformanceConfigLatencyOptimized',
  },
});

const BedrockLatencyConfigSupportedModels = Object.freeze([
  BedrockNovaModel.US_NOVA_PRO_V1,
]);

const BedrockMutuallyExclusiveTemperatureAndTopPModels = Object.freeze([
  BedrockAnthropicModel.GLOBAL_CLAUDE_SONNET_4_6,
  BedrockAnthropicModel.GLOBAL_CLAUDE_SONNET_4_5,
  BedrockAnthropicModel.GLOBAL_CLAUDE_OPUS_4_6_V1,
  BedrockAnthropicModel.JP_CLAUDE_SONNET_4_6,
  BedrockAnthropicModel.JP_CLAUDE_SONNET_4_5,
  BedrockAnthropicModel.US_CLAUDE_SONNET_4_6,
  BedrockAnthropicModel.US_CLAUDE_SONNET_4_5,
  BedrockAnthropicModel.US_CLAUDE_OPUS_4_6_V1,
]);

const CrossRegionInferencePrefix = Object.freeze({
  GLOBAL: 'global.',
  JP: 'jp.',
  US: 'us.',
});

const DefaultLlm = Object.freeze({
  ID: 'llm-default',
  NAME: 'default-llm',
  TYPE: Type.BEDROCK_ANTHROPIC.value,
});

const ActionExecutionParams = Object.freeze({
  DEFAULT_OUTPUT: {
    jsonSchema: {
      type: 'object',
      properties: {
        errors: {
          type: 'array',
          items: {
            type: 'string',
          },
        },
        message: {
          type: 'string',
        },
        request: {
          type: 'object',
        },
        thinking_summary: {
          type: 'string',
        },
        source_llm_id: {
          type: 'string',
        },
      },
      required: ['message'],
    },
  },
  MESSAGES: [
    {
      content: [
        {
          contentBlockName: 'default-content',
          contentBlockType: 'text',
          textI18n: '__instructionWorkflowActionCustomPrompt',
        },
      ],
      role: MessageRole.USER.value,
    },
  ],
  GUARDRAILS: {
    version: 'DRAFT',
  },
});

export {
  ActionExecutionParams,
  BedrockAnthropicModel,
  BedrockGptOssModel,
  BedrockLatencyConfigSupportedModels,
  BedrockLlamaModel,
  BedrockMutuallyExclusiveTemperatureAndTopPModels,
  BedrockNovaModel,
  BedrockPerformanceConfigLatencyOption,
  CredentialType,
  CrossRegionInferencePrefix,
  DefaultLlm,
  DefaultParams,
  GeminiModel,
  MessageRole,
  Model,
  OpenAiModel,
  ThinkingBudgetMode,
  ThinkingEffort,
  ThinkingLevel,
  Type,
};
