import { Type as StateType } from '~/constants/StateConstant';
import * as IconConstant from './IconConstant';

const Base = Object.freeze({
  FETCH_INTERVAL: 3000,
});

const ViewMode = Object.freeze({
  TIMELINE: {
    value: 'timeline',
    icon: 'mdi-timeline-outline',
    tooltip: '__tooltipViewTimeline',
  },
  LIST: {
    value: 'list',
    icon: 'mdi-list-box-outline',
    tooltip: '__tooltipViewList',
  },
});

const Category = Object.freeze({
  STATE: {
    i18nTitle: '__fieldWorkflowExecutionCategoryState',
    value: 'state',
  },
  EVENT: {
    i18nTitle: '__fieldWorkflowExecutionCategoryEvent',
    value: 'event',
  },
});

const EventType = Object.freeze({
  CHOICE_STATE_ENTERED: {
    title: 'ChoiceStateEntered',
    value: 'ChoiceStateEntered',
    details: 'stateEnteredEventDetails',
    icon: 'mdi-location-enter',
    iconColor: 'text',
    stateType: StateType.CHOICE.value,
  },
  CHOICE_STATE_EXITED: {
    title: 'ChoiceStateExited',
    value: 'ChoiceStateExited',
    details: 'stateExitedEventDetails',
    icon: 'mdi-location-exit',
    iconColor: 'text',
    stateType: StateType.CHOICE.value,
  },
  EVALUATION_FAILED: {
    title: 'EvaluationFailed',
    value: 'EvaluationFailed',
    details: 'evaluationFailedEventDetails',
    icon: 'mdi-alert-circle',
    iconColor: IconConstant.Color.FAILED,
    stateType: null,
  },
  EXECUTION_ABORTED: {
    title: 'ExecutionAborted',
    value: 'ExecutionAborted',
    details: 'executionAbortedEventDetails',
    icon: 'mdi-stop-circle-outline',
    iconColor: 'text',
    stateType: null,
  },
  EXECUTION_FAILED: {
    title: 'ExecutionFailed',
    value: 'ExecutionFailed',
    details: 'executionFailedEventDetails',
    icon: 'mdi-alert-circle',
    iconColor: IconConstant.Color.FAILED,
    stateType: null,
  },
  EXECUTION_REDRIVEN: {
    title: 'ExecutionRedriven',
    value: 'ExecutionRedriven',
    details: 'executionRedrivenEventDetails',
    icon: 'mdi-refresh',
    iconColor: 'text',
    stateType: null,
  },
  EXECUTION_STARTED: {
    title: 'ExecutionStarted',
    value: 'ExecutionStarted',
    details: 'executionStartedEventDetails',
    icon: 'mdi-play-circle-outline',
    iconColor: 'text',
    stateType: null,
  },
  EXECUTION_SUCCEEDED: {
    title: 'ExecutionSucceeded',
    value: 'ExecutionSucceeded',
    details: 'executionSucceededEventDetails',
    icon: 'mdi-check-circle',
    iconColor: IconConstant.Color.SUCCEEDED,
    stateType: null,
  },
  EXECUTION_TIMED_OUT: {
    title: 'ExecutionTimedOut',
    value: 'ExecutionTimedOut',
    details: 'executionTimedOutEventDetails',
    icon: 'mdi-clock-alert-outline',
    iconColor: 'text',
    stateType: null,
  },
  FAIL_STATE_ENTERED: {
    title: 'FailStateEntered',
    value: 'FailStateEntered',
    details: 'stateEnteredEventDetails',
    icon: 'mdi-location-enter',
    iconColor: 'text',
    stateType: StateType.FAIL.value,
  },
  LAMBDA_FUNCTION_FAILED: {
    title: 'LambdaFunctionFailed',
    value: 'LambdaFunctionFailed',
    details: 'lambdaFunctionFailedEventDetails',
    icon: 'mdi-alert-circle',
    iconColor: IconConstant.Color.FAILED,
    stateType: StateType.TASK.value,
  },
  LAMBDA_FUNCTION_SCHEDULE_FAILED: {
    title: 'LambdaFunctionScheduleFailed',
    value: 'LambdaFunctionScheduleFailed',
    details: 'lambdaFunctionScheduleFailedEventDetails',
    icon: 'mdi-alert-circle',
    iconColor: IconConstant.Color.FAILED,
    stateType: StateType.TASK.value,
  },
  LAMBDA_FUNCTION_SCHEDULED: {
    title: 'LambdaFunctionScheduled',
    value: 'LambdaFunctionScheduled',
    details: 'lambdaFunctionScheduledEventDetails',
    icon: 'mdi-clock-outline',
    iconColor: 'text',
    stateType: StateType.TASK.value,
  },
  LAMBDA_FUNCTION_START_FAILED: {
    title: 'LambdaFunctionStartFailed',
    value: 'LambdaFunctionStartFailed',
    details: 'lambdaFunctionStartFailedEventDetails',
    icon: 'mdi-alert-circle',
    iconColor: IconConstant.Color.FAILED,
    stateType: StateType.TASK.value,
  },
  LAMBDA_FUNCTION_STARTED: {
    title: 'LambdaFunctionStarted',
    value: 'LambdaFunctionStarted',
    details: null,
    icon: 'mdi-play-circle-outline',
    iconColor: 'text',
    stateType: StateType.TASK.value,
  },
  LAMBDA_FUNCTION_SUCCEEDED: {
    title: 'LambdaFunctionSucceeded',
    value: 'LambdaFunctionSucceeded',
    details: 'lambdaFunctionSucceededEventDetails',
    icon: 'mdi-check-circle',
    iconColor: IconConstant.Color.SUCCEEDED,
    stateType: StateType.TASK.value,
  },
  LAMBDA_FUNCTION_TIMED_OUT: {
    title: 'LambdaFunctionTimedOut',
    value: 'LambdaFunctionTimedOut',
    details: 'lambdaFunctionTimedOutEventDetails',
    icon: 'mdi-clock-alert-outline',
    iconColor: 'text',
    stateType: StateType.TASK.value,
  },
  MAP_ITERATION_ABORTED: {
    title: 'MapIterationAborted',
    value: 'MapIterationAborted',
    details: 'mapIterationAbortedEventDetails',
    icon: 'mdi-stop-circle-outline',
    iconColor: 'text',
    stateType: StateType.MAP.value,
  },
  MAP_ITERATION_FAILED: {
    title: 'MapIterationFailed',
    value: 'MapIterationFailed',
    details: 'mapIterationFailedEventDetails',
    icon: 'mdi-alert-circle',
    iconColor: IconConstant.Color.FAILED,
    stateType: StateType.MAP.value,
  },
  MAP_ITERATION_STARTED: {
    title: 'MapIterationStarted',
    value: 'MapIterationStarted',
    details: 'mapIterationStartedEventDetails',
    icon: 'mdi-play-circle-outline',
    iconColor: 'text',
    stateType: StateType.MAP.value,
  },
  MAP_ITERATION_SUCCEEDED: {
    title: 'MapIterationSucceeded',
    value: 'MapIterationSucceeded',
    details: 'mapIterationSucceededEventDetails',
    icon: 'mdi-check-circle',
    iconColor: IconConstant.Color.SUCCEEDED,
    stateType: StateType.MAP.value,
  },
  MAP_RUN_ABORTED: {
    title: 'MapRunAborted',
    value: 'MapRunAborted',
    details: 'mapRunAbortedEventDetails',
    icon: 'mdi-stop-circle-outline',
    iconColor: 'text',
    stateType: null,
  },
  MAP_RUN_FAILED: {
    title: 'MapRunFailed',
    value: 'MapRunFailed',
    details: 'mapRunFailedEventDetails',
    icon: 'mdi-alert-circle',
    iconColor: IconConstant.Color.FAILED,
    stateType: StateType.MAP.value,
  },
  MAP_RUN_REDRIVEN: {
    title: 'MapRunRedriven',
    value: 'MapRunRedriven',
    details: 'mapRunRedrivenEventDetails',
    icon: 'mdi-refresh',
    iconColor: 'text',
    stateType: StateType.MAP.value,
  },
  MAP_RUN_STARTED: {
    title: 'MapRunStarted',
    value: 'MapRunStarted',
    details: 'mapRunStartedEventDetails',
    icon: 'mdi-play-circle-outline',
    iconColor: 'text',
    stateType: StateType.MAP.value,
  },
  MAP_RUN_SUCCEEDED: {
    title: 'MapRunSucceeded',
    value: 'MapRunSucceeded',
    details: 'mapRunSucceededEventDetails',
    icon: 'mdi-check-circle',
    iconColor: IconConstant.Color.SUCCEEDED,
    stateType: null,
  },
  MAP_STATE_ABORTED: {
    title: 'MapStateAborted',
    value: 'MapStateAborted',
    details: 'stateExitedEventDetails',
    icon: 'mdi-stop-circle-outline',
    iconColor: 'text',
    stateType: StateType.MAP.value,
  },
  MAP_STATE_ENTERED: {
    title: 'MapStateEntered',
    value: 'MapStateEntered',
    details: 'stateEnteredEventDetails',
    icon: 'mdi-location-enter',
    iconColor: 'text',
    stateType: StateType.MAP.value,
  },
  MAP_STATE_EXITED: {
    title: 'MapStateExited',
    value: 'MapStateExited',
    details: 'stateExitedEventDetails',
    icon: 'mdi-location-exit',
    iconColor: 'text',
    stateType: StateType.MAP.value,
  },
  MAP_STATE_FAILED: {
    title: 'MapStateFailed',
    value: 'MapStateFailed',
    details: null,
    icon: 'mdi-alert-circle',
    iconColor: IconConstant.Color.FAILED,
    stateType: StateType.MAP.value,
  },
  MAP_STATE_STARTED: {
    title: 'MapStateStarted',
    value: 'MapStateStarted',
    details: 'mapStateStartedEventDetails',
    icon: 'mdi-play-circle-outline',
    iconColor: 'text',
    stateType: StateType.MAP.value,
  },
  MAP_STATE_SUCCEEDED: {
    title: 'MapStateSucceeded',
    value: 'MapStateSucceeded',
    details: null,
    icon: 'mdi-check-circle',
    iconColor: IconConstant.Color.SUCCEEDED,
    stateType: StateType.MAP.value,
  },
  PARALLEL_STATE_ABORTED: {
    title: 'ParallelStateAborted',
    value: 'ParallelStateAborted',
    details: 'stateExitedEventDetails',
    icon: 'mdi-stop-circle-outline',
    iconColor: 'text',
    stateType: StateType.PARALLEL.value,
  },
  PARALLEL_STATE_ENTERED: {
    title: 'ParallelStateEntered',
    value: 'ParallelStateEntered',
    details: 'stateEnteredEventDetails',
    icon: 'mdi-location-enter',
    iconColor: 'text',
    stateType: StateType.PARALLEL.value,
  },
  PARALLEL_STATE_EXITED: {
    title: 'ParallelStateExited',
    value: 'ParallelStateExited',
    details: 'stateExitedEventDetails',
    icon: 'mdi-location-exit',
    iconColor: 'text',
    stateType: StateType.PARALLEL.value,
  },
  PARALLEL_STATE_FAILED: {
    title: 'ParallelStateFailed',
    value: 'ParallelStateFailed',
    details: 'stateExitedEventDetails',
    icon: 'mdi-alert-circle',
    iconColor: IconConstant.Color.FAILED,
    stateType: StateType.PARALLEL.value,
  },
  PARALLEL_STATE_STARTED: {
    title: 'ParallelStateStarted',
    value: 'ParallelStateStarted',
    details: null,
    icon: 'mdi-play-circle-outline',
    iconColor: 'text',
    stateType: StateType.PARALLEL.value,
  },
  PARALLEL_STATE_SUCCEEDED: {
    title: 'ParallelStateSucceeded',
    value: 'ParallelStateSucceeded',
    details: null,
    icon: 'mdi-check-circle',
    iconColor: IconConstant.Color.SUCCEEDED,
    stateType: StateType.PARALLEL.value,
  },
  PASS_STATE_ENTERED: {
    title: 'PassStateEntered',
    value: 'PassStateEntered',
    details: 'stateEnteredEventDetails',
    icon: 'mdi-location-enter',
    iconColor: 'text',
    stateType: StateType.PASS.value,
  },
  PASS_STATE_EXITED: {
    title: 'PassStateExited',
    value: 'PassStateExited',
    details: 'stateExitedEventDetails',
    icon: 'mdi-location-exit',
    iconColor: 'text',
    stateType: StateType.PASS.value,
  },
  SUCCEED_STATE_ENTERED: {
    title: 'SucceedStateEntered',
    value: 'SucceedStateEntered',
    details: 'stateEnteredEventDetails',
    icon: 'mdi-location-enter',
    iconColor: 'text',
    stateType: StateType.SUCCEED.value,
  },
  SUCCEED_STATE_EXITED: {
    title: 'SucceedStateExited',
    value: 'SucceedStateExited',
    details: 'stateExitedEventDetails',
    icon: 'mdi-location-exit',
    iconColor: 'text',
    stateType: StateType.SUCCEED.value,
  },
  TASK_FAILED: {
    title: 'TaskFailed',
    value: 'TaskFailed',
    details: 'taskFailedEventDetails',
    icon: 'mdi-alert-circle',
    iconColor: IconConstant.Color.FAILED,
    stateType: StateType.TASK.value,
  },
  TASK_SCHEDULED: {
    title: 'TaskScheduled',
    value: 'TaskScheduled',
    details: 'taskScheduledEventDetails',
    icon: 'mdi-clock-outline',
    iconColor: 'text',
    stateType: StateType.TASK.value,
  },
  TASK_START_FAILED: {
    title: 'TaskStartFailed',
    value: 'TaskStartFailed',
    details: 'taskStartFailedEventDetails',
    icon: 'mdi-alert-circle',
    iconColor: IconConstant.Color.FAILED,
    stateType: StateType.TASK.value,
  },
  TASK_STARTED: {
    title: 'TaskStarted',
    value: 'TaskStarted',
    details: 'taskStartedEventDetails',
    icon: 'mdi-play-circle-outline',
    iconColor: 'text',
    stateType: StateType.TASK.value,
  },
  TASK_STATE_ABORTED: {
    title: 'TaskStateAborted',
    value: 'TaskStateAborted',
    details: null,
    icon: 'mdi-stop-circle-outline',
    iconColor: 'text',
    stateType: StateType.TASK.value,
  },
  TASK_STATE_ENTERED: {
    title: 'TaskStateEntered',
    value: 'TaskStateEntered',
    details: 'stateEnteredEventDetails',
    icon: 'mdi-location-enter',
    iconColor: 'text',
    stateType: StateType.TASK.value,
  },
  TASK_STATE_EXITED: {
    title: 'TaskStateExited',
    value: 'TaskStateExited',
    details: 'stateExitedEventDetails',
    icon: 'mdi-location-exit',
    iconColor: 'text',
    stateType: StateType.TASK.value,
  },
  TASK_SUBMIT_FAILED: {
    title: 'TaskSubmitFailed',
    value: 'TaskSubmitFailed',
    details: 'taskSubmitFailedEventDetails',
    icon: 'mdi-alert-circle',
    iconColor: IconConstant.Color.FAILED,
    stateType: StateType.TASK.value,
  },
  TASK_SUBMITTED: {
    title: 'TaskSubmitted',
    value: 'TaskSubmitted',
    details: 'taskSubmittedEventDetails',
    icon: 'mdi-send-circle-outline',
    iconColor: 'text',
    stateType: StateType.TASK.value,
  },
  TASK_SUCCEEDED: {
    title: 'TaskSucceeded',
    value: 'TaskSucceeded',
    details: 'taskSucceededEventDetails',
    icon: 'mdi-check-circle',
    iconColor: IconConstant.Color.SUCCEEDED,
    stateType: StateType.TASK.value,
  },
  TASK_TIMED_OUT: {
    title: 'TaskTimedOut',
    value: 'TaskTimedOut',
    details: 'taskTimedOutEventDetails',
    icon: 'mdi-clock-alert-outline',
    iconColor: 'text',
    stateType: StateType.TASK.value,
  },
  WAIT_STATE_ABORTED: {
    title: 'WaitStateAborted',
    value: 'WaitStateAborted',
    details: null,
    icon: 'mdi-stop-circle-outline',
    iconColor: 'text',
    stateType: StateType.WAIT.value,
  },
  WAIT_STATE_ENTERED: {
    title: 'WaitStateEntered',
    value: 'WaitStateEntered',
    details: 'stateEnteredEventDetails',
    icon: 'mdi-location-enter',
    iconColor: 'text',
    stateType: StateType.WAIT.value,
  },
  WAIT_STATE_EXITED: {
    title: 'WaitStateExited',
    value: 'WaitStateExited',
    details: 'stateExitedEventDetails',
    icon: 'mdi-location-exit',
    iconColor: 'text',
    stateType: StateType.WAIT.value,
  },
});

const ProgressNodeDimension = Object.freeze({
  GENERAL_NODE_WIDTH: 200,
  GENERAL_NODE_HEIGHT: 48,
  TERMINAL_NODE_WIDTH: 16,
  TERMINAL_NODE_HEIGHT: 16,
});

export {
  Base,
  Category,
  EventType,
  ProgressNodeDimension,
  ViewMode,
};
