const AuthType = Object.freeze({
  OAUTH: 'oauth',
  API_KEY: 'api_key',
  NONE: 'none',
});

const Preset = Object.freeze([
  {
    id: 'canva',
    name: 'Canva',
    description: '__subtitleMcpServerPresetCanva',
    iconPath: '/images/icons/presets/canva.svg',
    popularityRank: 6,
    authType: AuthType.OAUTH,
    endpointUrl: 'https://mcp.canva.com/mcp',
  },
  {
    id: 'notion',
    name: 'Notion',
    description: '__subtitleMcpServerPresetNotion',
    iconPath: '/images/icons/presets/notion.svg',
    popularityRank: 5,
    authType: AuthType.OAUTH,
    endpointUrl: 'https://mcp.notion.com/mcp',
  },
  {
    id: 'monday_com',
    name: 'monday.com',
    description: '__subtitleMcpServerPresetMondayCom',
    iconPath: '/images/icons/presets/monday_com.svg',
    popularityRank: 7,
    authType: AuthType.OAUTH,
    endpointUrl: 'https://mcp.monday.com/mcp',
  },
  {
    id: 'linear',
    name: 'Linear',
    description: '__subtitleMcpServerPresetLinear',
    iconPath: '/images/icons/presets/linear.svg',
    popularityRank: 8,
    authType: AuthType.OAUTH,
    endpointUrl: 'https://mcp.linear.app/mcp',
  },
  {
    id: 'tavily',
    name: 'Tavily',
    description: '__subtitleMcpServerPresetTavily',
    iconPath: '/images/icons/presets/tavily.svg',
    popularityRank: 12,
    authType: AuthType.OAUTH,
    endpointUrl: 'https://mcp.tavily.com/mcp/',
  },
  {
    id: 'paypal',
    name: 'PayPal',
    description: '__subtitleMcpServerPresetPayPal',
    iconPath: '/images/icons/presets/paypal.svg',
    popularityRank: 10,
    authType: AuthType.OAUTH,
    endpointUrl: 'https://mcp.paypal.com/mcp',
  },
  {
    id: 'cloudflare',
    name: 'Cloudflare',
    description: '__subtitleMcpServerPresetCloudflare',
    iconPath: '/images/icons/presets/cloudflare.svg',
    popularityRank: 11,
    authType: AuthType.OAUTH,
    endpointUrl: 'https://mcp.cloudflare.com/mcp',
  },
  {
    id: 'github',
    name: 'GitHub',
    description: '__subtitleMcpServerPresetGitHub',
    iconPath: '/images/icons/presets/github.svg',
    popularityRank: 1,
    authType: AuthType.API_KEY,
    endpointUrl: 'https://api.githubcopilot.com/mcp',
  },
  {
    id: 'google_maps',
    name: 'Google Maps',
    description: '__subtitleMcpServerPresetGoogleMaps',
    iconPath: '/images/icons/presets/google_maps.png',
    popularityRank: 9,
    authType: AuthType.API_KEY,
    apiKeyHeader: 'X-Goog-Api-Key',
    endpointUrl: 'https://mapstools.googleapis.com/mcp',
  },
  {
    id: 'google_drive',
    name: 'Google Drive',
    description: '__subtitleMcpServerPresetGoogleDrive',
    iconPath: '/images/icons/presets/google_drive.svg',
    popularityRank: 3,
    authType: AuthType.API_KEY,
    apiKeyHeader: 'X-Goog-Api-Key',
    endpointUrl: 'https://drivemcp.googleapis.com/mcp/v1',
  },
  {
    id: 'gmail',
    name: 'Gmail',
    description: '__subtitleMcpServerPresetGmail',
    iconPath: '/images/icons/presets/gmail.svg',
    popularityRank: 2,
    authType: AuthType.API_KEY,
    apiKeyHeader: 'X-Goog-Api-Key',
    endpointUrl: 'https://gmailmcp.googleapis.com/mcp/v1',
  },
  {
    id: 'google_calendar',
    name: 'Google Calendar',
    description: '__subtitleMcpServerPresetGoogleCalendar',
    iconPath: '/images/icons/presets/google_calendar.svg',
    popularityRank: 4,
    authType: AuthType.API_KEY,
    apiKeyHeader: 'X-Goog-Api-Key',
    endpointUrl: 'https://calendarmcp.googleapis.com/mcp',
  },
  {
    id: 'deepwiki',
    name: 'DeepWiki',
    description: '__subtitleMcpServerPresetDeepWiki',
    iconPath: '/images/icons/presets/deepwiki.png',
    popularityRank: 13,
    authType: AuthType.NONE,
    endpointUrl: 'https://mcp.deepwiki.com/mcp',
  },
  {
    id: 'context7',
    name: 'Context7',
    description: '__subtitleMcpServerPresetContext7',
    iconPath: '/images/icons/presets/context7.svg',
    popularityRank: 14,
    authType: AuthType.NONE,
    endpointUrl: 'https://mcp.context7.com/mcp',
  },
]);

export {
  AuthType,
  Preset,
};
