import * as ChunkerConstant from './ChunkerConstant';
import * as ConnectorConstant from './ConnectorConstant';
import * as EmbeddingModelConstant from './EmbeddingModelConstant';
import * as FeatureConstant from './FeatureConstant';
import * as IconConstant from './IconConstant';
import * as KnowledgeBaseConstant from './KnowledgeBaseConstant';
import * as LlmConstant from './LlmConstant';
import * as LoaderConstant from './LoaderConstant';
import * as McpServerConstant from './McpServerConstant';
import * as RankerConstant from './RankerConstant';
import * as RetrieverConstant from './RetrieverConstant';
import * as SearchEngineConstant from './SearchEngineConstant';
import * as StorageConstant from './StorageConstant';
import * as VariableConstant from './VariableConstant';

const Type = Object.freeze({
  AGENT: {
    i18nTitle: '__fieldAgent',
    value: 'agent',
    icon: IconConstant.Base.AGENT,
    module: 'agent',
    path: 'agents',
    id: 'agentId',
    listKey: 'agents',
    getEndpoint: '/resource/get-agent',
    getEndpointId: 'agent_id',
    favoriteFilterField: 'agent_id',
    createRequestResourceName: 'agent_name',
    type: null,
    allowDeleteRecursively: true,
    allowDownloadWorkflowDefinition: false,
    allowPublishTemplate: false,
    allowValidate: false,
  },
  CHUNKER: {
    i18nTitle: '__fieldChunker',
    value: 'chunker',
    icon: 'mdi-file-tree',
    module: 'chunker',
    path: 'chunkers',
    id: 'chunkerId',
    typeField: 'chunkerType',
    listKey: 'chunkers',
    getEndpoint: '/resource/get-chunker',
    getEndpointId: 'chunker_id',
    favoriteFilterField: 'chunker_id',
    createRequestResourceName: 'chunker_name',
    requiredFeatures: [FeatureConstant.Name.OPENSEARCH],
    type: ChunkerConstant.Type,
    allowDeleteRecursively: true,
    allowDownloadWorkflowDefinition: false,
    allowPublishTemplate: false,
    allowValidate: false,
  },
  CONNECTOR: {
    i18nTitle: '__fieldConnector',
    value: 'connector',
    icon: 'mdi-link-variant',
    module: 'connector',
    path: 'connectors',
    id: 'connectorId',
    typeField: 'connectorType',
    listKey: 'connectors',
    getEndpoint: '/resource/get-connector',
    getEndpointId: 'connector_id',
    favoriteFilterField: 'connector_id',
    createRequestResourceName: 'connector_name',
    type: ConnectorConstant.Type,
    allowDeleteRecursively: true,
    allowDownloadWorkflowDefinition: false,
    allowPublishTemplate: false,
    allowValidate: true,
  },
  DATASET: {
    i18nTitle: '__fieldDataset',
    value: 'dataset',
    icon: 'mdi-database',
    module: 'dataset',
    path: 'datasets',
    id: 'datasetId',
    listKey: 'datasets',
    getEndpoint: '/resource/get-dataset',
    getEndpointId: 'dataset_id',
    favoriteFilterField: 'dataset_id',
    createRequestResourceName: 'dataset_name',
    type: null,
    allowDeleteRecursively: true,
    allowDownloadWorkflowDefinition: false,
    allowPublishTemplate: false,
    allowValidate: false,
  },
  EMBEDDING_MODEL: {
    i18nTitle: '__fieldEmbeddingModel',
    value: 'embedding_model',
    icon: 'mdi-vector-link',
    module: 'embeddingModel',
    path: 'embedding-models',
    id: 'embeddingModelId',
    typeField: 'embeddingModelType',
    listKey: 'embeddingModels',
    getEndpoint: '/resource/get-embedding-model',
    getEndpointId: 'embedding_model_id',
    favoriteFilterField: 'embedding_model_id',
    createRequestResourceName: 'embedding_model_name',
    type: EmbeddingModelConstant.Type,
    allowDeleteRecursively: true,
    allowDownloadWorkflowDefinition: false,
    allowPublishTemplate: false,
    allowValidate: false,
  },
  KNOWLEDGE_BASE: {
    i18nTitle: '__fieldKnowledgeBase',
    value: 'knowledge_base',
    icon: 'mdi-library',
    module: 'knowledgeBase',
    path: 'knowledge-bases',
    id: 'knowledgeBaseId',
    typeField: 'knowledgeBaseType',
    listKey: 'knowledgeBases',
    getEndpoint: '/resource/get-knowledge-base',
    getEndpointId: 'knowledge_base_id',
    favoriteFilterField: 'knowledge_base_id',
    createRequestResourceName: 'knowledge_base_name',
    requiredFeatures: [FeatureConstant.Name.OPENSEARCH],
    type: KnowledgeBaseConstant.Type,
    allowDeleteRecursively: true,
    allowDownloadWorkflowDefinition: false,
    allowPublishTemplate: false,
    allowValidate: false,
  },
  LAMBDA_FUNCTION: {
    i18nTitle: '__fieldLambdaFunction',
    value: 'lambda_function',
    icon: 'mdi-lambda',
    module: 'lambdaFunction',
    path: 'lambda-functions',
    id: 'lambdaFunctionId',
    listKey: 'lambdaFunctions',
    getEndpoint: '/resource/get-lambda-function',
    getEndpointId: 'lambda_function_id',
    favoriteFilterField: 'lambda_function_id',
    createRequestResourceName: 'lambda_function_name',
    type: null,
    allowDeleteRecursively: true,
    allowDownloadWorkflowDefinition: false,
    allowPublishTemplate: false,
    allowValidate: false,
  },
  LLM: {
    i18nTitle: '__fieldLlm',
    value: 'llm',
    icon: 'mdi-brain',
    module: 'llm',
    path: 'llms',
    id: 'llmId',
    typeField: 'llmType',
    listKey: 'llms',
    getEndpoint: '/resource/get-llm',
    getEndpointId: 'llm_id',
    favoriteFilterField: 'llm_id',
    createRequestResourceName: 'llm_name',
    type: LlmConstant.Type,
    allowDeleteRecursively: true,
    allowDownloadWorkflowDefinition: false,
    allowPublishTemplate: false,
    allowValidate: true,
  },
  LOADER: {
    i18nTitle: '__fieldLoader',
    value: 'loader',
    icon: 'mdi-folder-open',
    module: 'loader',
    path: 'loaders',
    id: 'loaderId',
    typeField: 'loaderType',
    listKey: 'loaders',
    getEndpoint: '/resource/get-loader',
    getEndpointId: 'loader_id',
    favoriteFilterField: 'loader_id',
    createRequestResourceName: 'loader_name',
    requiredFeatures: [FeatureConstant.Name.OPENSEARCH],
    type: LoaderConstant.Type,
    allowDeleteRecursively: true,
    allowDownloadWorkflowDefinition: false,
    allowPublishTemplate: false,
    allowValidate: false,
  },
  MCP_SERVER: {
    i18nTitle: '__fieldMcpServer',
    value: 'mcp_server',
    iconPath: '/images/icons/mcp.svg',
    iconPathMaskColor: 'white',
    module: 'mcpServer',
    path: 'mcp-servers',
    id: 'mcpServerId',
    typeField: 'mcpServerType',
    listKey: 'mcpServers',
    getEndpoint: '/resource/get-mcp-server',
    getEndpointId: 'mcp_server_id',
    favoriteFilterField: 'mcp_server_id',
    createRequestResourceName: 'mcp_server_name',
    type: McpServerConstant.Type,
    allowDeleteRecursively: false,
    allowDownloadWorkflowDefinition: false,
    allowPublishTemplate: false,
    allowValidate: false,
  },
  RANKER: {
    i18nTitle: '__fieldRanker',
    value: 'ranker',
    icon: 'mdi-sort-variant',
    module: 'ranker',
    path: 'rankers',
    id: 'rankerId',
    typeField: 'rankerType',
    listKey: 'rankers',
    getEndpoint: '/resource/get-ranker',
    getEndpointId: 'ranker_id',
    favoriteFilterField: 'ranker_id',
    createRequestResourceName: 'ranker_name',
    type: RankerConstant.Type,
    allowDeleteRecursively: true,
    allowDownloadWorkflowDefinition: false,
    allowPublishTemplate: false,
    allowValidate: false,
  },
  RETRIEVER: {
    i18nTitle: '__fieldRetriever',
    value: 'retriever',
    icon: 'mdi-magnify',
    module: 'retriever',
    path: 'retrievers',
    id: 'retrieverId',
    typeField: 'retrieverType',
    listKey: 'retrievers',
    getEndpoint: '/resource/get-retriever',
    getEndpointId: 'retriever_id',
    favoriteFilterField: 'retriever_id',
    createRequestResourceName: 'retriever_name',
    requiredFeatures: [FeatureConstant.Name.OPENSEARCH],
    type: RetrieverConstant.Type,
    allowDeleteRecursively: true,
    allowDownloadWorkflowDefinition: false,
    allowPublishTemplate: false,
    allowValidate: false,
  },
  SEARCH_ENGINE: {
    i18nTitle: '__fieldSearchEngine',
    value: 'search_engine',
    icon: 'mdi-search-web',
    module: 'searchEngine',
    path: 'search-engines',
    id: 'searchEngineId',
    typeField: 'searchEngineType',
    listKey: 'searchEngines',
    getEndpoint: '/resource/get-search-engine',
    getEndpointId: 'search_engine_id',
    favoriteFilterField: 'search_engine_id',
    createRequestResourceName: 'search_engine_name',
    type: SearchEngineConstant.Type,
    allowDeleteRecursively: true,
    allowDownloadWorkflowDefinition: false,
    allowPublishTemplate: false,
    allowValidate: true,
  },
  SKILL: {
    i18nTitle: '__fieldSkill',
    value: 'skill',
    icon: 'mdi-shape-plus',
    module: 'skill',
    path: 'skills',
    id: 'skillId',
    listKey: 'skills',
    getEndpoint: '/resource/get-skill',
    getEndpointId: 'skill_id',
    favoriteFilterField: 'skill_id',
    createRequestResourceName: 'skill_name',
    type: null,
    allowDeleteRecursively: true,
    allowDownloadWorkflowDefinition: false,
    allowPublishTemplate: false,
    allowValidate: false,
  },
  STORAGE: {
    i18nTitle: '__fieldStorage',
    value: 'storage',
    icon: 'mdi-file-cabinet',
    module: 'storage',
    path: 'storages',
    id: 'storageId',
    listKey: 'storages',
    getEndpoint: '/resource/get-storage',
    getEndpointId: 'storage_id',
    favoriteFilterField: 'storage_id',
    createRequestResourceName: 'storage_name',
    type: StorageConstant.Type,
    allowDeleteRecursively: true,
    allowDownloadWorkflowDefinition: false,
    allowPublishTemplate: false,
    allowValidate: false,
  },
  TEMPLATE: {
    i18nTitle: '__fieldTemplate',
    value: 'template',
    icon: 'mdi-comment-text',
    module: 'template',
    path: 'templates',
    id: 'templateId',
    listKey: 'templates',
    getEndpoint: '/resource/get-template',
    getEndpointId: 'template_id',
    favoriteFilterField: 'template_id',
    createRequestResourceName: 'template_name',
    type: null,
    allowDeleteRecursively: true,
    allowDownloadWorkflowDefinition: false,
    allowPublishTemplate: false,
    allowValidate: false,
  },
  VARIABLE: {
    i18nTitle: '__fieldVariable',
    value: 'variable',
    icon: 'mdi-variable',
    module: 'variable',
    path: 'variables',
    id: 'variableId',
    typeField: 'variableType',
    listKey: 'variables',
    getEndpoint: '/resource/get-variable',
    getEndpointId: 'variable_id',
    favoriteFilterField: 'variable_id',
    createRequestResourceName: 'variable_name',
    type: VariableConstant.Type,
    allowDeleteRecursively: true,
    allowDownloadWorkflowDefinition: false,
    allowPublishTemplate: false,
    allowValidate: false,
  },
  WORKFLOW: {
    i18nTitle: '__fieldWorkflow',
    value: 'workflow',
    icon: IconConstant.Base.WORKFLOW,
    module: 'workflow',
    path: 'workflows',
    id: 'workflowId',
    listKey: 'workflows',
    getEndpoint: '/resource/get-workflow',
    getEndpointId: 'workflow_id',
    favoriteFilterField: 'workflow_id',
    createRequestResourceName: 'workflow_name',
    type: null,
    allowDeleteRecursively: true,
    allowDownloadWorkflowDefinition: true,
    allowPublishTemplate: true,
    allowValidate: false,
  },
});

const AgentCreateMode = Object.freeze({
  FROM_BLANK: {
    value: 'from_blank',
    i18nTitle: '__titleCreateFromBlank',
    icon: 'mdi-file-plus',
  },
  FROM_AGENT_BUILDER: {
    value: 'from_agent_builder',
    i18nTitle: '__titleCreateFromAgentBuilder',
    icon: IconConstant.Base.AGENT_BUILDER,
  },
});

const WorkflowCreateMode = Object.freeze({
  FROM_BLANK: {
    value: 'from_blank',
    i18nTitle: '__titleCreateFromBlank',
    i18nSubtitle: '__subtitleCreateFromBlank',
    icon: 'mdi-file-plus',
  },
  FROM_TEMPLATE: {
    value: 'from_template',
    i18nTitle: '__titleCreateFromTemplate',
    icon: IconConstant.Base.WORKFLOW_TEMPLATE,
  },
  FROM_WORKFLOW_DEFINITION: {
    value: 'from_workflow_definition',
    i18nTitle: '__titleCreateFromDefinition',
    i18nSubtitle: '__subtitleCreateFromDefinition',
    icon: 'mdi-file-upload',
  },
});

const WorkflowTemplateCreateMode = Object.freeze({
  FROM_BLANK: {
    value: 'from_blank',
    i18nTitle: '__titleCreateFromBlank',
    icon: 'mdi-file-plus',
  },
  FROM_EXISTING_WORKFLOW: {
    value: 'from_existing_workflow',
    i18nTitle: '__titleCreateFromExistingWorkflow',
    icon: IconConstant.Base.WORKFLOW,
  },
});

const IdAliases = Object.freeze({
  drafterLlmId: Type.LLM.id,
  verifierLlmId: Type.LLM.id,
});

const DependencyType = Object.freeze({
  DEPENDENT: {
    i18nTitle: '__titleDependent',
    notFoundTitle: '__titleNoDependent',
    notFoundInstruction: '__instructionNoDependent',
    value: 'dependent',
    icon: IconConstant.Base.DEPENDENCY,
  },
  DEPENDENCY: {
    i18nTitle: '__titleDependency',
    notFoundTitle: '__titleNoDependency',
    notFoundInstruction: '__instructionNoDependency',
    value: 'dependency',
    icon: IconConstant.Base.DEPENDENCY,
  },
});

const ViewMode = Object.freeze({
  CARD: {
    value: 'card',
    icon: 'mdi-view-grid-outline',
    tooltip: '__tooltipViewCard',
  },
  LIST: {
    value: 'list',
    icon: 'mdi-view-list-outline',
    tooltip: '__tooltipViewList',
  },
});

export {
  AgentCreateMode,
  DependencyType,
  IdAliases,
  Type,
  ViewMode,
  WorkflowCreateMode,
  WorkflowTemplateCreateMode,
};
