"""Glue table column definitions: (column_name, glue_type) lists.

table.real_data holds the real hackathon dataset schemas registered by the CDK
stack; table.raw / table.curated hold the synthetic lake schemas, retained for
reference.
"""

from table.curated import (
    AGG_FLEET_DAILY_COLUMNS,
    DIM_PORT_COLUMNS,
    FACT_ALERT_COLUMNS,
    FACT_ANOMALY_COLUMNS,
    FACT_MAINTENANCE_EVENT_COLUMNS,
    FACT_MAINTENANCE_RECOMMENDATION_COLUMNS,
    FACT_PERFORMANCE_DAILY_COLUMNS,
    FACT_PERFORMANCE_INDICATOR_COLUMNS,
    FACT_RECOMMENDATION_COLUMNS,
    FACT_SPEED_PROFILE_COLUMNS,
    FACT_UWI_COLUMNS,
    FACT_VOYAGE_COLUMNS,
)
from table.raw import (
    FUEL_PRICE_COLUMNS,
    MAINTENANCE_EVENT_COLUMNS,
    NOON_REPORT_COLUMNS,
    REFERENCE_CURVE_COLUMNS,
    UWI_COLUMNS,
    VESSEL_MASTER_COLUMNS,
)
from table.real_data import (
    FACT_SHIP_ALERT_COLUMNS,
    FACT_SHIP_ANOMALY_COLUMNS,
    FACT_SHIP_DAILY_COLUMNS,
    FACT_SHIP_MAINTENANCE_RECOMMENDATION_COLUMNS,
    MAINTENANCE_COLUMNS,
    SHIP_IDS,
    VESSEL_COLUMNS,
    VT_FD_COLUMNS,
)

__all__ = [
    'AGG_FLEET_DAILY_COLUMNS',
    'DIM_PORT_COLUMNS',
    'FACT_ALERT_COLUMNS',
    'FACT_ANOMALY_COLUMNS',
    'FACT_SHIP_ALERT_COLUMNS',
    'FACT_SHIP_ANOMALY_COLUMNS',
    'FACT_SHIP_DAILY_COLUMNS',
    'FACT_SHIP_MAINTENANCE_RECOMMENDATION_COLUMNS',
    'FACT_MAINTENANCE_EVENT_COLUMNS',
    'FACT_MAINTENANCE_RECOMMENDATION_COLUMNS',
    'FACT_PERFORMANCE_DAILY_COLUMNS',
    'FACT_PERFORMANCE_INDICATOR_COLUMNS',
    'FACT_RECOMMENDATION_COLUMNS',
    'FACT_SPEED_PROFILE_COLUMNS',
    'FACT_UWI_COLUMNS',
    'FACT_VOYAGE_COLUMNS',
    'FUEL_PRICE_COLUMNS',
    'MAINTENANCE_COLUMNS',
    'MAINTENANCE_EVENT_COLUMNS',
    'NOON_REPORT_COLUMNS',
    'REFERENCE_CURVE_COLUMNS',
    'SHIP_IDS',
    'UWI_COLUMNS',
    'VESSEL_COLUMNS',
    'VESSEL_MASTER_COLUMNS',
    'VT_FD_COLUMNS',
]
