import colors from 'vuetify/util/colors';
import { defineVuetifyConfiguration } from 'vuetify-nuxt-module/custom-configuration';

const light = {
  colors: {
    aborted: colors.grey.base,
    action: '#e3b737',
    actionButton: '#fbfbfb',
    background: '#f4f5fa',
    backgroundScale1: '#edeff5',
    backgroundScale2: '#ffffff',
    backgroundScale3: '#e2e4ea',
    backgroundScale4: '#ababab',
    backgroundScale5: '#fbfbfb',
    backgroundTooltip: '#f4f5fa',
    canceled: '#ababab',
    categoryIcon: '#8c57ff',
    critical: colors.red.base,
    deleting: colors.red.base,
    disabled: '#c9c9c9',
    error: colors.red.base,
    failed: colors.red.base,
    fallback: '#eeb3c3',
    flow: '#9bb8e7',
    inputBorder: '#ababab',
    pending: '#ffd580',
    primary: '#8c57ff',
    primaryLight: '#a47dfd',
    processed: '#ababab',
    ready: colors.green.base,
    running: colors.blue.base,
    success: '#679e4a',
    succeeded: colors.green.base,
    active: colors.green.base,
    inactive: colors.grey.base,
    tableScrollButton: '#edeff5',
    text: '#2e263d',
    updating: '#ff9800',
    referencePathPrefix: colors.orange.base,
    referencePathSuffix: colors.cyan.base,
    vueFlowBackgroundPattern: '#c9c9c9',
    assistantMessageBubble: '#e2e4ea',
    userMessageBubble: '#e0e0e0',
    gradientButtonBorderColor1: '#a47dfd',
    gradientButtonBorderColor2: '#9bb8e7',
    thinkingStepDotColor: '#cfd2da',
  },
};

const dark = {
  colors: {
    aborted: colors.grey.base,
    action: '#e3b737',
    actionButton: '#4d4570',
    background: '#28243d',
    backgroundScale1: '#3d3759',
    backgroundScale2: '#312d4b',
    backgroundScale3: '#514b6e',
    backgroundScale4: '#7f7d90',
    backgroundScale5: '#4d4570',
    backgroundTooltip: '#3d3759',
    canceled: '#7f7d90',
    categoryIcon: '#ffffff',
    critical: '#f57c92',
    deleting: colors.red.base,
    disabled: '#7f7d90',
    error: '#f57c92',
    failed: colors.red.base,
    fallback: '#eeb3c3',
    flow: '#9bb8e7',
    inputBorder: '#7f7d90',
    pending: '#ffd580',
    primary: '#8c57ff',
    primaryLight: '#a47dfd',
    processed: '#7f7d90',
    ready: colors.green.base,
    running: colors.blue.base,
    success: '#679e4a',
    succeeded: colors.green.base,
    active: colors.green.base,
    inactive: colors.grey.base,
    tableScrollButton: '#514b6e',
    text: '#e7e3fc',
    updating: '#ff9800',
    referencePathPrefix: colors.orange.base,
    referencePathSuffix: colors.cyan.base,
    vueFlowBackgroundPattern: '#514b6e',
    assistantMessageBubble: '#3d3759',
    userMessageBubble: '#8c57ff',
    gradientButtonBorderColor1: '#8c57ff',
    gradientButtonBorderColor2: '#2b86c5',
    thinkingStepDotColor: '#4e4673',
  },
};

export default defineVuetifyConfiguration({
  theme: {
    defaultTheme: 'light',
    themes: {
      dark,
      light,
    },
  },
  labComponents: [
    'VDateInput',
  ],
  icons: {
    sets: [
      {
        name: 'mdi',
        cdn: 'https://cdn.jsdelivr.net/npm/@mdi/font@7/css/materialdesignicons.min.css',
      },
    ],
  },
});
